SET CREDIT_COST_USD = 3;

/*
No fan-out — the deduplication subqueries on BRZ_RAW_ALERTS and BRZ_RAW_TRANSACTIONS are working correctly. The table has exactly one row per calendar date with no inflated counts.
*/
CREATE OR REPLACE TABLE ADMIN_DB.OPS.FRAUD_INTELLIGENCE_COST_VALUE_MAPPING AS
WITH DAILY_FRAUD_METRICS AS (
    SELECT
        DATE_TRUNC('DAY', gld.ALERT_DATE)::DATE AS VALUE_DATE,
        COUNT(*) AS ALERTS_PROCESSED,
        SUM(CASE WHEN gld.IS_FRAUD_DERIVED = TRUE THEN 1 ELSE 0 END) AS FRAUD_ALERTS_DETECTED,
        SUM(CASE WHEN gld.SAR_FILED = TRUE THEN 1 ELSE 0 END) AS SAR_FILED_COUNT,
        SUM(CASE WHEN gld.IS_FRAUD_DERIVED = TRUE THEN txn.TRANSACTION_AMOUNT ELSE 0 END) AS FRAUD_AMOUNT_PROTECTED,
        AVG(gld.ML_FRAUD_SCORE) AS AVG_ML_FRAUD_SCORE,
        SUM(CASE WHEN gld.ML_RISK_TIER = 'HIGH' THEN 1 ELSE 0 END) AS HIGH_RISK_ALERT_COUNT,
        DIV0NULL(
            SUM(CASE WHEN gld.IS_FRAUD_DERIVED = TRUE THEN 1 ELSE 0 END)::FLOAT,
            COUNT(*)::FLOAT
        ) AS FRAUD_DETECTION_RATE
    FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHED gld
    LEFT JOIN (
        SELECT ALERT_ID, MAX(TRANSACTION_ID) AS TRANSACTION_ID
        FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS
        GROUP BY ALERT_ID
    ) brz
        ON gld.ALERT_ID = brz.ALERT_ID
    LEFT JOIN (
        SELECT TRANSACTION_ID, MAX(TRANSACTION_AMOUNT) AS TRANSACTION_AMOUNT
        FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS
        GROUP BY TRANSACTION_ID
    ) txn
        ON brz.TRANSACTION_ID = txn.TRANSACTION_ID
    GROUP BY DATE_TRUNC('DAY', gld.ALERT_DATE)::DATE
),
DAILY_COMPUTE_COST AS (
    SELECT
        DATE_TRUNC('DAY', START_TIME)::DATE AS COST_DATE,
        SUM(CREDITS_USED) AS TOTAL_CREDITS,
        SUM(CREDITS_USED_COMPUTE - CREDITS_ATTRIBUTED_COMPUTE_QUERIES) AS IDLE_CREDITS,
        SUM(CREDITS_ATTRIBUTED_COMPUTE_QUERIES) AS PRODUCTIVE_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE WAREHOUSE_NAME = 'AGENT_DEMO_WH'
    GROUP BY DATE_TRUNC('DAY', START_TIME)::DATE
)
SELECT
    f.VALUE_DATE,
    'AGENT_DEMO_WH' AS WAREHOUSE_NAME,
    c.TOTAL_CREDITS,
    c.IDLE_CREDITS,
    c.PRODUCTIVE_CREDITS,
    f.ALERTS_PROCESSED,
    f.FRAUD_ALERTS_DETECTED,
    f.SAR_FILED_COUNT,
    f.FRAUD_AMOUNT_PROTECTED,
    f.AVG_ML_FRAUD_SCORE,
    f.HIGH_RISK_ALERT_COUNT,
    f.FRAUD_DETECTION_RATE,
    DIV0NULL(f.FRAUD_AMOUNT_PROTECTED, c.TOTAL_CREDITS) AS FRAUD_AMOUNT_PER_CREDIT,
    DIV0NULL(c.TOTAL_CREDITS * 3, f.SAR_FILED_COUNT) AS SAR_COST_PER_FILING
FROM DAILY_FRAUD_METRICS f
LEFT JOIN DAILY_COMPUTE_COST c
    ON f.VALUE_DATE = c.COST_DATE
WHERE f.VALUE_DATE >= DATEADD('DAY', -90, CURRENT_DATE())
ORDER BY f.VALUE_DATE;

SELECT COUNT(DISTINCT DATE_TRUNC('DAY', START_TIME)::DATE) AS distinct_cost_dates FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY WHERE WAREHOUSE_NAME = 'AGENT_DEMO_WH' AND DATE_TRUNC('DAY', START_TIME)::DATE >= DATEADD('DAY', -90, CURRENT_DATE());

SELECT COUNT(*) AS mapping_rows, MIN(VALUE_DATE) AS min_date, MAX(VALUE_DATE) AS max_date FROM ADMIN_DB.OPS.FRAUD_INTELLIGENCE_COST_VALUE_MAPPING;

SELECT SUM(FRAUD_ALERTS_DETECTED) AS fraud_in_mapping, (SELECT COUNT(*) FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHED WHERE IS_FRAUD_DERIVED = TRUE AND DATE_TRUNC('DAY', ALERT_DATE)::DATE >= DATEADD('DAY', -90, CURRENT_DATE())) AS fraud_in_source, SUM(SAR_FILED_COUNT) AS sar_in_mapping, (SELECT COUNT(*) FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHED WHERE SAR_FILED = TRUE AND DATE_TRUNC('DAY', ALERT_DATE)::DATE >= DATEADD('DAY', -90, CURRENT_DATE())) AS sar_in_source FROM ADMIN_DB.OPS.FRAUD_INTELLIGENCE_COST_VALUE_MAPPING;

SELECT SUM(ALERTS_PROCESSED) AS total_alerts_in_mapping, (SELECT COUNT(*) FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHED WHERE DATE_TRUNC('DAY', ALERT_DATE)::DATE >= DATEADD('DAY', -90, CURRENT_DATE())) AS total_alerts_in_source FROM ADMIN_DB.OPS.FRAUD_INTELLIGENCE_COST_VALUE_MAPPING;



