SHOW TABLES IN SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE;

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM DEMO_DEV.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'FRAUD_INTELLIGENCE'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

SELECT 'BRZ_ANALYST_DECISIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(DECISION_TIMESTAMP) AS MIN_TS, MAX(DECISION_TIMESTAMP) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS;
SELECT 'BRZ_RAW_ALERTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(ALERT_DATE) AS MIN_TS, MAX(ALERT_DATE) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS;
SELECT 'BRZ_RAW_CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(INGESTED_AT) AS MIN_TS, MAX(INGESTED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_CUSTOMERS;
SELECT 'BRZ_RAW_INVESTIGATION_DOCS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(INGESTED_AT) AS MIN_TS, MAX(INGESTED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_INVESTIGATION_DOCS;
SELECT 'BRZ_RAW_RULE_DEFINITIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(INGESTED_AT) AS MIN_TS, MAX(INGESTED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_RULE_DEFINITIONS;
SELECT 'BRZ_RAW_TRANSACTIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(TRANSACTION_DATE) AS MIN_TS, MAX(TRANSACTION_DATE) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS;
SELECT 'BRZ_RAW_VELOCITY_EVENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(EVENT_TIMESTAMP) AS MIN_TS, MAX(EVENT_TIMESTAMP) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_VELOCITY_EVENTS;
SELECT 'GLD_ALERT_ENRICHED' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(ALERT_DATE) AS MIN_TS, MAX(ALERT_DATE) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHED;
SELECT 'GLD_ALERT_ENRICHMENT_WITH_SCORING' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(ALERT_DATE) AS MIN_TS, MAX(ALERT_DATE) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHMENT_WITH_SCORING;
SELECT 'GLD_CUSTOMER_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(DBT_LOADED_AT) AS MIN_TS, MAX(DBT_LOADED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_CUSTOMER_PROFILE;
SELECT 'GLD_ML_TRAINING_SET' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(TRANSACTION_DATE) AS MIN_TS, MAX(TRANSACTION_DATE) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ML_TRAINING_SET;
SELECT 'GLD_VELOCITY_COUNTERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(LAST_UPDATED) AS MIN_TS, MAX(LAST_UPDATED) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_VELOCITY_COUNTERS;
SELECT 'SLV_FRAUD_EVAL_DATA' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, NULL AS MIN_TS, NULL AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.SLV_FRAUD_EVAL_DATA;
SELECT 'SLV_FRAUD_FEATURES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, NULL AS MIN_TS, NULL AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.SLV_FRAUD_FEATURES;
SELECT 'SLV_FRAUD_MODEL_METADATA' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(LAST_TRAINED_AT) AS MIN_TS, MAX(LAST_TRAINED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.SLV_FRAUD_MODEL_METADATA;
SELECT 'SLV_INVESTIGATION_KNOWLEDGE_BASE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(LOADED_AT) AS MIN_TS, MAX(LOADED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.SLV_INVESTIGATION_KNOWLEDGE_BASE;
SELECT 'SLV_MODEL_PERFORMANCE_LOG' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(LOGGED_AT) AS MIN_TS, MAX(LOGGED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.SLV_MODEL_PERFORMANCE_LOG;
SELECT 'SLV_RULE_CODE_KNOWLEDGE_MAP' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(LOADED_AT) AS MIN_TS, MAX(LOADED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.SLV_RULE_CODE_KNOWLEDGE_MAP;
SELECT 'STG_ANALYST_DECISIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(DECISION_DATE) AS MIN_TS, MAX(DECISION_DATE) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.STG_ANALYST_DECISIONS;
SELECT 'STG_RAW_ALERTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(ALERT_DATE) AS MIN_TS, MAX(ALERT_DATE) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.STG_RAW_ALERTS;
SELECT 'STG_RAW_CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(INGESTED_AT) AS MIN_TS, MAX(INGESTED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.STG_RAW_CUSTOMERS;
SELECT 'STG_RAW_INVESTIGATION_DOCS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(INGESTED_AT) AS MIN_TS, MAX(INGESTED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.STG_RAW_INVESTIGATION_DOCS;
SELECT 'STG_RAW_RULE_DEFINITIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(INGESTED_AT) AS MIN_TS, MAX(INGESTED_AT) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.STG_RAW_RULE_DEFINITIONS;
SELECT 'STG_RAW_TRANSACTIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(TRANSACTION_DATE) AS MIN_TS, MAX(TRANSACTION_DATE) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.STG_RAW_TRANSACTIONS;
SELECT 'STG_RAW_VELOCITY_EVENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, MIN(EVENT_TIMESTAMP) AS MIN_TS, MAX(EVENT_TIMESTAMP) AS MAX_TS FROM DEMO_DEV.FRAUD_INTELLIGENCE.STG_RAW_VELOCITY_EVENTS;
