-- ============================================================
-- Monitoring Queries for RETAIL_CATEGORY_ANALYTICS_AGENT
-- Run against SNOWFLAKE.ACCOUNT_USAGE or INFORMATION_SCHEMA
-- ============================================================

-- 1. Invocation count (last 7 days) — grouped by day
SELECT
    DATE_TRUNC('day', START_TIME) AS query_date,
    COUNT(*) AS invocation_count
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TEXT ILIKE '%RETAIL_CATEGORY_ANALYTICS_AGENT%'
  AND START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY query_date
ORDER BY query_date DESC;

-- 2. Tool call breakdown — sample queries with latency
SELECT
    QUERY_TEXT,
    TOTAL_ELAPSED_TIME / 1000.0 AS latency_seconds,
    START_TIME,
    ROWS_PRODUCED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TEXT ILIKE '%RETAIL_CATEGORY_ANALYTICS_AGENT%'
  AND START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC
LIMIT 50;

-- 3. Eval results trend — pass rate over time (from eval results table)
SELECT
    DATE_TRUNC('day', EVAL_TIMESTAMP) AS eval_date,
    AVG(OVERALL_SCORE) AS avg_score,
    COUNT(*) AS eval_count,
    SUM(CASE WHEN OVERALL_SCORE >= 0.80 THEN 1 ELSE 0 END)::FLOAT / COUNT(*) AS pass_rate
FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.AGENT_EVAL_RESULTS
GROUP BY eval_date
ORDER BY eval_date DESC;

-- 4. Slowest queries — performance triage (> 10s)
SELECT
    QUERY_ID,
    QUERY_TEXT,
    TOTAL_ELAPSED_TIME / 1000.0 AS latency_seconds,
    START_TIME,
    EXECUTION_STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TEXT ILIKE '%RETAIL_CATEGORY_ANALYTICS_AGENT%'
  AND TOTAL_ELAPSED_TIME > 10000
  AND START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY TOTAL_ELAPSED_TIME DESC
LIMIT 20;

-- 5. Failed queries — error monitoring
SELECT
    QUERY_ID,
    QUERY_TEXT,
    ERROR_CODE,
    ERROR_MESSAGE,
    START_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TEXT ILIKE '%RETAIL_CATEGORY_ANALYTICS_AGENT%'
  AND EXECUTION_STATUS = 'FAIL'
  AND START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC
LIMIT 20;

-- 6. Credit consumption — budget tracking
SELECT
    DATE_TRUNC('day', START_TIME) AS usage_date,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS cloud_credits,
    COUNT(*) AS query_count
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE WAREHOUSE_NAME = 'RETAIL_CATEGORY_ANALYTICS_WH'
  AND QUERY_TEXT ILIKE '%RETAIL_CATEGORY_ANALYTICS_AGENT%'
  AND START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY usage_date
ORDER BY usage_date DESC;
