{{
    config(
        materialized='view',
        tags=['staging']
    )
}}

SELECT
    DECISION_ID,
    ALERT_ID,
    TRANSACTION_ID,
    CUSTOMER_ID,
    ANALYST_ID,
    DECISION,
    SAR_RECOMMENDED,
    SAR_FILED,
    SAR_FILED_DATE,
    SAR_FILED_TIMESTAMP,
    ML_SCORE_AT_DECISION,
    AGENT_RECOMMENDATION,
    AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY,
    RULE_TRIGGERED,
    RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET,
    CONFIDENCE_LEVEL,
    DECISION_NOTES,
    AGENT_SCORED_AT,
    AGENT_REASONED_AT,
    DECISION_TIMESTAMP,
    SOURCE_SYSTEM,
    INGESTED_AT
FROM {{ source('fraud_intelligence_bronze', 'BRZ_ANALYST_DECISIONS') }}
WHERE DECISION_ID IS NOT NULL
