USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;

-- ============================================================
-- MIGRATION SCRIPT: DEMO_DEV.GOLD -> DEMO_DEV.FRAUD_INTELLIGENCE
-- This script copies (not drops) existing objects into the new schema
-- with proper BRZ_/SLV_/GLD_ naming convention.
-- Original GOLD schema is preserved until manual verification.
-- ============================================================

-- Step 1: Copy Gold-layer tables
CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHED
    CLONE DEMO_DEV.GOLD.ALERT_ENRICHED;

CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ML_TRAINING_SET
    CLONE DEMO_DEV.GOLD.ML_TRAINING_SET;

-- Hybrid Tables cannot be cloned; use CTAS
CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.GLD_CUSTOMER_PROFILE AS
    SELECT * FROM DEMO_DEV.GOLD.CUSTOMER_PROFILE;

CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.GLD_VELOCITY_COUNTERS AS
    SELECT * FROM DEMO_DEV.GOLD.VELOCITY_COUNTERS;

-- Step 2: Copy Silver-layer tables
CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_FRAUD_MODEL_METADATA
    CLONE DEMO_DEV.GOLD.FRAUD_MODEL_METADATA;

CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_MODEL_PERFORMANCE_LOG
    CLONE DEMO_DEV.GOLD.MODEL_PERFORMANCE_LOG;

CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_FRAUD_EVAL_DATA
    CLONE DEMO_DEV.GOLD.FRAUD_EVAL_DATA;

CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_INVESTIGATION_KNOWLEDGE_BASE
    CLONE DEMO_DEV.GOLD.INVESTIGATION_KNOWLEDGE_BASE;

CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_RULE_CODE_KNOWLEDGE_MAP
    CLONE DEMO_DEV.GOLD.RULE_CODE_KNOWLEDGE_MAP;

-- Step 3: Recreate views in new schema with renamed references
CREATE OR REPLACE VIEW DEMO_DEV.FRAUD_INTELLIGENCE.SLV_FRAUD_FEATURES AS
SELECT
    TRANSACTION_ID,
    CUSTOMER_ID,
    TRANSACTION_AMOUNT,
    TRANSACTION_TYPE,
    MERCHANT_CATEGORY,
    CHANNEL,
    ACCOUNT_AGE_DAYS,
    CREDIT_LIMIT,
    CURRENT_BALANCE,
    ACCOUNT_TYPE,
    UTILIZATION_RATIO,
    RISK_SEGMENT,
    KYC_COMPLETE,
    ADDRESS_CHANGE_COUNT,
    IS_SYNTHETIC_FLAG,
    IS_MERGER_DUP_FLAG,
    CUSTOMER_TENURE_DAYS,
    PRIOR_ALERT_COUNT_CUSTOMER,
    ALERT_WITHIN_7D,
    TXN_COUNT_1H,
    TXN_COUNT_24H,
    TXN_AMOUNT_1H,
    TXN_AMOUNT_24H,
    DISTINCT_MERCHANTS_24H
FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ML_TRAINING_SET;

CREATE OR REPLACE VIEW DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHMENT_WITH_SCORING AS
SELECT
    ae.ALERT_ID,
    ae.CUSTOMER_ID,
    ae.ALERT_DATE,
    ae.RULE_CODE,
    ae.RULE_DESCRIPTION,
    ae.ALERT_RISK_SCORE,
    ae.ALERT_STATUS,
    ae.ANALYST_ID,
    ae.DISPOSITION,
    ae.SAR_FILED,
    ae.IS_FRAUD_DERIVED,
    cp.FULL_NAME,
    cp.RISK_SEGMENT,
    cp.KYC_COMPLETE,
    cp.IS_SYNTHETIC_FLAG,
    cp.ACCOUNT_COUNT,
    cp.MIN_ACCOUNT_AGE_DAYS,
    cp.MAX_ACCOUNT_AGE_DAYS,
    cp.PRIOR_ALERT_COUNT,
    CASE
        WHEN cp.CUSTOMER_TENURE_DAYS < 90 THEN 'HIGH'
        WHEN cp.CUSTOMER_TENURE_DAYS < 365 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS TENURE_RISK_TIER,
    CASE
        WHEN cp.PRIOR_ALERT_COUNT >= 5 THEN 'HIGH'
        WHEN cp.PRIOR_ALERT_COUNT >= 2 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ALERT_HISTORY_RISK_TIER,
    vc.TXN_COUNT_1H,
    vc.TXN_COUNT_24H,
    vc.TXN_AMOUNT_1H,
    vc.TXN_AMOUNT_24H,
    vc.DISTINCT_MERCHANTS_24H,
    vc.RECENT_TXN_COUNT,
    vc.RECENT_TXN_AMOUNT,
    vc.FRAUD_RATE_7D,
    ROUND(
        (ae.ALERT_RISK_SCORE * 0.30) +
        (CASE WHEN cp.CUSTOMER_TENURE_DAYS < 90 THEN 80 WHEN cp.CUSTOMER_TENURE_DAYS < 365 THEN 50 ELSE 20 END * 0.25) +
        (CASE WHEN cp.PRIOR_ALERT_COUNT >= 5 THEN 90 WHEN cp.PRIOR_ALERT_COUNT >= 2 THEN 60 ELSE 20 END * 0.20) +
        (CASE WHEN cp.IS_SYNTHETIC_FLAG THEN 95 ELSE 10 END * 0.15) +
        (COALESCE(vc.FRAUD_RATE_7D, 0) * 100 * 0.10),
        2
    ) AS COMPOSITE_RISK_SCORE,
    CASE
        WHEN ROUND(
            (ae.ALERT_RISK_SCORE * 0.30) +
            (CASE WHEN cp.CUSTOMER_TENURE_DAYS < 90 THEN 80 WHEN cp.CUSTOMER_TENURE_DAYS < 365 THEN 50 ELSE 20 END * 0.25) +
            (CASE WHEN cp.PRIOR_ALERT_COUNT >= 5 THEN 90 WHEN cp.PRIOR_ALERT_COUNT >= 2 THEN 60 ELSE 20 END * 0.20) +
            (CASE WHEN cp.IS_SYNTHETIC_FLAG THEN 95 ELSE 10 END * 0.15) +
            (COALESCE(vc.FRAUD_RATE_7D, 0) * 100 * 0.10), 2) >= 70 THEN 'CRITICAL'
        WHEN ROUND(
            (ae.ALERT_RISK_SCORE * 0.30) +
            (CASE WHEN cp.CUSTOMER_TENURE_DAYS < 90 THEN 80 WHEN cp.CUSTOMER_TENURE_DAYS < 365 THEN 50 ELSE 20 END * 0.25) +
            (CASE WHEN cp.PRIOR_ALERT_COUNT >= 5 THEN 90 WHEN cp.PRIOR_ALERT_COUNT >= 2 THEN 60 ELSE 20 END * 0.20) +
            (CASE WHEN cp.IS_SYNTHETIC_FLAG THEN 95 ELSE 10 END * 0.15) +
            (COALESCE(vc.FRAUD_RATE_7D, 0) * 100 * 0.10), 2) >= 45 THEN 'HIGH'
        ELSE 'STANDARD'
    END AS ENRICHMENT_PRIORITY,
    CURRENT_TIMESTAMP() AS ENRICHMENT_TIMESTAMP,
    TIMESTAMPDIFF(HOUR, ae.ALERT_DATE, CURRENT_TIMESTAMP()) AS HOURS_SINCE_ALERT
FROM DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHED ae
LEFT JOIN DEMO_DEV.FRAUD_INTELLIGENCE.GLD_CUSTOMER_PROFILE cp
    ON ae.CUSTOMER_ID = cp.CUSTOMER_ID
LEFT JOIN DEMO_DEV.FRAUD_INTELLIGENCE.GLD_VELOCITY_COUNTERS vc
    ON ae.CUSTOMER_ID = vc.CUSTOMER_ID;

-- Step 4: Tag migrated objects with DATA_LAYER
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ALERT_ENRICHED SET TAG DATA_LAYER = 'GOLD';
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.GLD_ML_TRAINING_SET SET TAG DATA_LAYER = 'GOLD';
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.GLD_CUSTOMER_PROFILE SET TAG DATA_LAYER = 'GOLD';
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.GLD_VELOCITY_COUNTERS SET TAG DATA_LAYER = 'GOLD';
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_FRAUD_MODEL_METADATA SET TAG DATA_LAYER = 'SILVER';
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_MODEL_PERFORMANCE_LOG SET TAG DATA_LAYER = 'SILVER';
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_FRAUD_EVAL_DATA SET TAG DATA_LAYER = 'SILVER';
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_INVESTIGATION_KNOWLEDGE_BASE SET TAG DATA_LAYER = 'SILVER';
ALTER TABLE DEMO_DEV.FRAUD_INTELLIGENCE.SLV_RULE_CODE_KNOWLEDGE_MAP SET TAG DATA_LAYER = 'SILVER';

-- NOTE: The original GOLD schema is NOT dropped.
-- Verify all data migrated correctly before manual cleanup.
