USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;
USE SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE;

CREATE TABLE IF NOT EXISTS DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID VARCHAR(50) NOT NULL,
    ALERT_ID VARCHAR(50) NOT NULL,
    TRANSACTION_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    ANALYST_ID VARCHAR(50),
    DECISION VARCHAR(30),
    SAR_RECOMMENDED BOOLEAN,
    SAR_FILED BOOLEAN,
    SAR_FILED_DATE DATE,
    SAR_FILED_TIMESTAMP TIMESTAMP_LTZ,
    ML_SCORE_AT_DECISION NUMBER(5,4),
    AGENT_RECOMMENDATION VARCHAR(50),
    AGENT_CONFIDENCE VARCHAR(20),
    AGENT_REASONING_SUMMARY VARCHAR(2000),
    RULE_TRIGGERED VARCHAR(20),
    RULE_ML_AGREEMENT BOOLEAN,
    SAR_THRESHOLD_MET BOOLEAN,
    CONFIDENCE_LEVEL VARCHAR(20),
    DECISION_NOTES VARCHAR(1000),
    AGENT_SCORED_AT TIMESTAMP_LTZ,
    AGENT_REASONED_AT TIMESTAMP_LTZ,
    DECISION_TIMESTAMP TIMESTAMP_LTZ,
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'AGENT_ASSISTED_TRIAGE',
    INGESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS IS 'Agent-assisted analyst fraud decisions with ML probabilistic scores, LLM reasoning summaries, and SAR filing decisions';

INSERT INTO BRZ_RAW_TRANSACTIONS (TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT, TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY, DEVICE_ID, IP_ADDRESS)
SELECT
    TRANSACTION_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    TRANSACTION_DATE,
    TRANSACTION_AMOUNT,
    TRANSACTION_TYPE,
    MERCHANT_CATEGORY,
    CHANNEL,
    'MERCHANT_' || UNIFORM(1, 500, RANDOM()) AS MERCHANT_NAME,
    'US' AS MERCHANT_COUNTRY,
    'DEV_' || UUID_STRING() AS DEVICE_ID,
    CONCAT(UNIFORM(10,255,RANDOM())::VARCHAR, '.', UNIFORM(0,255,RANDOM())::VARCHAR, '.', UNIFORM(0,255,RANDOM())::VARCHAR, '.', UNIFORM(0,255,RANDOM())::VARCHAR) AS IP_ADDRESS
FROM DEMO_DEV.GOLD.ML_TRAINING_SET;

INSERT INTO BRZ_RAW_ALERTS (ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION, ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED, TRANSACTION_ID)
SELECT
    ALERT_ID,
    CUSTOMER_ID,
    ALERT_DATE,
    RULE_CODE,
    RULE_DESCRIPTION,
    ALERT_RISK_SCORE,
    ALERT_STATUS,
    ANALYST_ID,
    DISPOSITION,
    SAR_FILED,
    NULL AS TRANSACTION_ID
FROM DEMO_DEV.GOLD.ALERT_ENRICHED;

INSERT INTO BRZ_RAW_CUSTOMERS (CUSTOMER_ID, FULL_NAME, DATE_OF_BIRTH, SSN_LAST_FOUR, EMAIL, PHONE, ADDRESS_LINE_1, CITY, STATE, ZIP_CODE, COUNTRY, RISK_SEGMENT, KYC_COMPLETE, IS_SYNTHETIC_FLAG, IS_MERGER_DUP_FLAG, CUSTOMER_SINCE, ACCOUNT_COUNT)
SELECT
    CUSTOMER_ID,
    FULL_NAME,
    DATEADD(YEAR, -UNIFORM(25, 70, RANDOM()), CURRENT_DATE()) AS DATE_OF_BIRTH,
    LPAD(UNIFORM(1000, 9999, RANDOM())::VARCHAR, 4, '0') AS SSN_LAST_FOUR,
    LOWER(REPLACE(FULL_NAME, ' ', '.')) || '@example.com' AS EMAIL,
    '+1' || LPAD(UNIFORM(2000000000, 9999999999, RANDOM())::VARCHAR, 10, '0') AS PHONE,
    UNIFORM(100, 9999, RANDOM())::VARCHAR || ' Main St' AS ADDRESS_LINE_1,
    'City_' || UNIFORM(1, 50, RANDOM())::VARCHAR AS CITY,
    'ST' AS STATE,
    LPAD(UNIFORM(10000, 99999, RANDOM())::VARCHAR, 5, '0') AS ZIP_CODE,
    'US' AS COUNTRY,
    RISK_SEGMENT,
    KYC_COMPLETE,
    IS_SYNTHETIC_FLAG,
    IS_MERGER_DUP_FLAG,
    DATEADD(DAY, -CUSTOMER_TENURE_DAYS, CURRENT_DATE()) AS CUSTOMER_SINCE,
    ACCOUNT_COUNT
FROM DEMO_DEV.GOLD.CUSTOMER_PROFILE;

INSERT INTO BRZ_RAW_VELOCITY_EVENTS (EVENT_ID, CUSTOMER_ID, EVENT_TIMESTAMP, TXN_COUNT_1H, TXN_COUNT_24H, TXN_AMOUNT_1H, TXN_AMOUNT_24H, DISTINCT_MERCHANTS_24H, RECENT_TXN_COUNT, RECENT_TXN_AMOUNT, FRAUD_RATE_7D)
SELECT
    'EVT_' || ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID) AS EVENT_ID,
    CUSTOMER_ID,
    LAST_UPDATED AS EVENT_TIMESTAMP,
    TXN_COUNT_1H,
    TXN_COUNT_24H,
    TXN_AMOUNT_1H,
    TXN_AMOUNT_24H,
    DISTINCT_MERCHANTS_24H,
    RECENT_TXN_COUNT,
    RECENT_TXN_AMOUNT,
    FRAUD_RATE_7D
FROM DEMO_DEV.GOLD.VELOCITY_COUNTERS;

INSERT INTO BRZ_RAW_INVESTIGATION_DOCS (DOC_ID, DOC_TITLE, DOC_CONTENT, DOC_CATEGORY, EFFECTIVE_DATE)
SELECT
    'DOC_' || ROW_NUMBER() OVER (ORDER BY TITLE) AS DOC_ID,
    TITLE AS DOC_TITLE,
    CONTENT AS DOC_CONTENT,
    CATEGORY AS DOC_CATEGORY,
    CURRENT_DATE() AS EFFECTIVE_DATE
FROM DEMO_DEV.GOLD.INVESTIGATION_KNOWLEDGE_BASE;

INSERT INTO BRZ_RAW_RULE_DEFINITIONS (RULE_CODE, RULE_NAME, RULE_DESCRIPTION, RULE_CATEGORY, RISK_WEIGHT, IS_ACTIVE, CREATED_DATE)
SELECT
    RULE_CODE,
    RULE_CODE AS RULE_NAME,
    DESCRIPTION AS RULE_DESCRIPTION,
    CATEGORY AS RULE_CATEGORY,
    UNIFORM(1.0, 10.0, RANDOM()) AS RISK_WEIGHT,
    TRUE AS IS_ACTIVE,
    CURRENT_DATE() AS CREATED_DATE
FROM DEMO_DEV.GOLD.RULE_CODE_KNOWLEDGE_MAP;

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD(SEQ4()::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD(MOD(SEQ4(), 50)::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD(MOD(SEQ4(), 50)::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 1440), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(5000 + UNIFORM(0, 15000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'PURCHASE'
        WHEN 1 THEN 'TRANSFER'
        WHEN 2 THEN 'CASH_ADVANCE'
        ELSE 'WITHDRAWAL'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'ELECTRONICS'
        WHEN 2 THEN 'JEWELRY'
        WHEN 3 THEN 'TRAVEL'
        ELSE 'CRYPTO'
    END AS MERCHANT_CATEGORY,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'ATM'
        ELSE 'MOBILE'
    END AS CHANNEL,
    'MERCHANT_FRAUD_' || MOD(SEQ4(), 20)::VARCHAR AS MERCHANT_NAME,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'NG'
        WHEN 1 THEN 'RU'
        WHEN 2 THEN 'CN'
        WHEN 3 THEN 'IR'
        ELSE 'US'
    END AS MERCHANT_COUNTRY,
    'DEV_FRAUD_' || MOD(SEQ4(), 30)::VARCHAR AS DEVICE_ID,
    '192.168.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((1200 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((170 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((170 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 168), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(3000 + UNIFORM(0, 17000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'TRANSFER'
        WHEN 1 THEN 'PURCHASE'
        ELSE 'WITHDRAWAL'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'JEWELRY'
        WHEN 1 THEN 'ELECTRONICS'
        WHEN 2 THEN 'LUXURY'
        ELSE 'TRAVEL'
    END AS MERCHANT_CATEGORY,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'MOBILE'
        ELSE 'BRANCH'
    END AS CHANNEL,
    'MERCHANT_INTL_' || MOD(SEQ4(), 20)::VARCHAR AS MERCHANT_NAME,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'NG'
        WHEN 1 THEN 'IR'
        WHEN 2 THEN 'KP'
        WHEN 3 THEN 'SY'
        ELSE 'MM'
    END AS MERCHANT_COUNTRY,
    'DEV_UNKNOWN_' || MOD(SEQ4(), 40)::VARCHAR AS DEVICE_ID,
    '185.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR || '.1' AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));


INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((600 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((100 + MOD(SEQ4(), 40))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((100 + MOD(SEQ4(), 40))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 4320), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(8000 + UNIFORM(0, 12000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    'CASH_ADVANCE' AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'CASH'
        WHEN 1 THEN 'CRYPTO'
        ELSE 'MONEY_TRANSFER'
    END AS MERCHANT_CATEGORY,
    'ATM' AS CHANNEL,
    'ATM_FRAUD_' || MOD(SEQ4(), 25)::VARCHAR AS MERCHANT_NAME,
    'US' AS MERCHANT_COUNTRY,
    'DEV_CASH_' || MOD(SEQ4(), 15)::VARCHAR AS DEVICE_ID,
    '172.16.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((300 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((50 + MOD(SEQ4(), 50))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((50 + MOD(SEQ4(), 50))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 2880), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(5000 + UNIFORM(0, 20000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'PURCHASE'
        WHEN 1 THEN 'TRANSFER'
        ELSE 'CASH_ADVANCE'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'ELECTRONICS'
        WHEN 1 THEN 'GIFT_CARDS'
        WHEN 2 THEN 'CRYPTO'
        ELSE 'ONLINE'
    END AS MERCHANT_CATEGORY,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'MOBILE'
        ELSE 'ATM'
    END AS CHANNEL,
    'MERCHANT_SYNTH_' || MOD(SEQ4(), 15)::VARCHAR AS MERCHANT_NAME,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'US'
        WHEN 1 THEN 'NG'
        ELSE 'GH'
    END AS MERCHANT_COUNTRY,
    'DEV_SYNTH_' || MOD(SEQ4(), 20)::VARCHAR AS DEVICE_ID,
    '10.0.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((900 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('second', -1 * MOD(SEQ4(), 3600), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(1000 + UNIFORM(0, 8000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'PURCHASE'
        WHEN 1 THEN 'TRANSFER'
        ELSE 'WITHDRAWAL'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'ELECTRONICS'
        WHEN 2 THEN 'GIFT_CARDS'
        ELSE 'TRAVEL'
    END AS MERCHANT_CATEGORY,
    'ONLINE' AS CHANNEL,
    'MERCHANT_ATO_' || MOD(SEQ4(), 30)::VARCHAR AS MERCHANT_NAME,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'US'
        WHEN 1 THEN 'RU'
        WHEN 2 THEN 'CN'
        ELSE 'BR'
    END AS MERCHANT_COUNTRY,
    'DEV_ATO_' || MOD(SEQ4(), 5)::VARCHAR AS DEVICE_ID,
    '203.0.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((900 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('second', -1 * MOD(SEQ4(), 3600), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(1000 + UNIFORM(0, 8000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'PURCHASE'
        WHEN 1 THEN 'TRANSFER'
        ELSE 'WITHDRAWAL'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'ELECTRONICS'
        WHEN 2 THEN 'GIFT_CARDS'
        ELSE 'TRAVEL'
    END AS MERCHANT_CATEGORY,
    'ONLINE' AS CHANNEL,
    'MERCHANT_ATO_' || MOD(SEQ4(), 30)::VARCHAR AS MERCHANT_NAME,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'US'
        WHEN 1 THEN 'RU'
        WHEN 2 THEN 'CN'
        ELSE 'BR'
    END AS MERCHANT_COUNTRY,
    'DEV_ATO_' || MOD(SEQ4(), 5)::VARCHAR AS DEVICE_ID,
    '203.0.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD(SEQ4()::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD(MOD(SEQ4(), 50)::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 72), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    'BUST_OUT_PATTERN' AS RULE_CODE,
    'Rule Code: BUST_OUT_PATTERN — Detection Logic and Thresholds' AS RULE_DESCRIPTION,
    ROUND(0.85 + UNIFORM(0, 0.15, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD(MOD(SEQ4(), 300)::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD((60 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD((50 + MOD(SEQ4(), 50))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 96), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    CASE MOD(SEQ4(), 2) WHEN 0 THEN 'SSN_VELOCITY' ELSE 'DEVICE_ANOMALY' END AS RULE_CODE,
    CASE MOD(SEQ4(), 2)
        WHEN 0 THEN 'Rule Code: SSN_VELOCITY — Detection Logic and Thresholds'
        ELSE 'Rule Code: DEVICE_ANOMALY — Detection Logic and Thresholds'
    END AS RULE_DESCRIPTION,
    ROUND(0.87 + UNIFORM(0, 0.13, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD((300 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD((120 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD((100 + MOD(SEQ4(), 40))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 120), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    'LARGE_CASH_ADVANCE' AS RULE_CODE,
    'Rule Code: LARGE_CASH_ADVANCE — Detection Logic and Thresholds' AS RULE_DESCRIPTION,
    ROUND(0.86 + UNIFORM(0, 0.14, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD((600 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD((180 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 2880), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    'VELOCITY_CHECK' AS RULE_CODE,
    'Rule Code: VELOCITY_CHECK — Detection Logic and Thresholds' AS RULE_DESCRIPTION,
    ROUND(0.88 + UNIFORM(0, 0.12, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD((900 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_CUSTOMERS (
    CUSTOMER_ID, FULL_NAME, DATE_OF_BIRTH, SSN_LAST_FOUR, EMAIL, PHONE,
    ADDRESS_LINE_1, CITY, STATE, ZIP_CODE, COUNTRY,
    RISK_SEGMENT, KYC_COMPLETE, IS_SYNTHETIC_FLAG, IS_MERGER_DUP_FLAG,
    CUSTOMER_SINCE, ACCOUNT_COUNT, SOURCE_SYSTEM
)
SELECT
    'FRAUD_CUST_' || LPAD(SEQ4()::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'Synthetic Person ' || SEQ4()::VARCHAR AS FULL_NAME,
    DATEADD('year', -1 * (20 + MOD(SEQ4(), 40)), CURRENT_DATE()) AS DATE_OF_BIRTH,
    LPAD(MOD(SEQ4() * 7919, 10000)::VARCHAR, 4, '0') AS SSN_LAST_FOUR,
    'fraud_user_' || SEQ4()::VARCHAR || '@tempmail.com' AS EMAIL,
    '555-' || LPAD(MOD(SEQ4(), 10000)::VARCHAR, 4, '0') AS PHONE,
    SEQ4()::VARCHAR || ' Fake Street' AS ADDRESS_LINE_1,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'Miami'
        WHEN 1 THEN 'Las Vegas'
        WHEN 2 THEN 'New York'
        WHEN 3 THEN 'Houston'
        ELSE 'Los Angeles'
    END AS CITY,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'FL'
        WHEN 1 THEN 'NV'
        WHEN 2 THEN 'NY'
        WHEN 3 THEN 'TX'
        ELSE 'CA'
    END AS STATE,
    LPAD(MOD(SEQ4() * 31, 100000)::VARCHAR, 5, '0') AS ZIP_CODE,
    'US' AS COUNTRY,
    'HIGH' AS RISK_SEGMENT,
    CASE WHEN MOD(SEQ4(), 3) = 0 THEN FALSE ELSE TRUE END AS KYC_COMPLETE,
    CASE WHEN MOD(SEQ4(), 2) = 0 THEN TRUE ELSE FALSE END AS IS_SYNTHETIC_FLAG,
    CASE WHEN MOD(SEQ4(), 10) = 0 THEN TRUE ELSE FALSE END AS IS_MERGER_DUP_FLAG,
    DATEADD('day', -1 * MOD(SEQ4(), 60), CURRENT_DATE()) AS CUSTOMER_SINCE,
    1 + MOD(SEQ4(), 3) AS ACCOUNT_COUNT,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 200));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_VELOCITY_EVENTS (
    EVENT_ID, CUSTOMER_ID, EVENT_TIMESTAMP, TXN_COUNT_1H, TXN_COUNT_24H,
    TXN_AMOUNT_1H, TXN_AMOUNT_24H, DISTINCT_MERCHANTS_24H,
    RECENT_TXN_COUNT, RECENT_TXN_AMOUNT, FRAUD_RATE_7D, SOURCE_SYSTEM
)
SELECT
    'FRAUD_EVT_' || LPAD(SEQ4()::VARCHAR, 5, '0') AS EVENT_ID,
    'FRAUD_CUST_' || LPAD(MOD(SEQ4(), 200)::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 1440), CURRENT_TIMESTAMP()) AS EVENT_TIMESTAMP,
    5 + MOD(SEQ4(), 15) AS TXN_COUNT_1H,
    15 + MOD(SEQ4(), 40) AS TXN_COUNT_24H,
    ROUND(3000 + UNIFORM(0, 12000, RANDOM())::NUMBER(10,2), 2) AS TXN_AMOUNT_1H,
    ROUND(8000 + UNIFORM(0, 30000, RANDOM())::NUMBER(10,2), 2) AS TXN_AMOUNT_24H,
    5 + MOD(SEQ4(), 10) AS DISTINCT_MERCHANTS_24H,
    10 + MOD(SEQ4(), 20) AS RECENT_TXN_COUNT,
    ROUND(5000 + UNIFORM(0, 20000, RANDOM())::NUMBER(10,2), 2) AS RECENT_TXN_AMOUNT,
    ROUND(0.15 + UNIFORM(0, 0.85, RANDOM())::NUMBER(8,6), 6) AS FRAUD_RATE_7D,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE, SAR_FILED_TIMESTAMP,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_' || LPAD((70 + SEQ4())::VARCHAR, 5, '0') AS DECISION_ID,
    'FRAUD_ALT_' || LPAD((60 + MOD(SEQ4(), 60))::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_TXN_' || LPAD((300 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((50 + MOD(SEQ4(), 50))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DECISION,
    TRUE AS SAR_RECOMMENDED,
    TRUE AS SAR_FILED,
    CURRENT_DATE() - MOD(SEQ4(), 5) AS SAR_FILED_DATE,
    DATEADD('hour', -1 * (24 + MOD(SEQ4(), 72)), CURRENT_TIMESTAMP()) AS SAR_FILED_TIMESTAMP,
    ROUND(0.85 + UNIFORM(0, 0.15, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'CONFIRM_FRAUD' AS AGENT_RECOMMENDATION,
    'HIGH' AS AGENT_CONFIDENCE,
    'Synthetic identity indicators: IS_SYNTHETIC_FLAG=TRUE, account age <60 days, SSN velocity anomaly detected. Multiple accounts opened with same device fingerprint. Aggregated transaction amount $' || (6000 + MOD(SEQ4() * 211, 14000))::VARCHAR || ' exceeds FinCEN SAR $5,000 threshold. LLM confirms pattern consistent with synthetic identity fraud typology.' AS AGENT_REASONING_SUMMARY,
    CASE MOD(SEQ4(), 2) WHEN 0 THEN 'SSN_VELOCITY' ELSE 'DEVICE_ANOMALY' END AS RULE_TRIGGERED,
    TRUE AS RULE_ML_AGREEMENT,
    TRUE AS SAR_THRESHOLD_MET,
    'HIGH' AS CONFIDENCE_LEVEL,
    'Synthetic identity confirmed via agent reasoning + ML score alignment. SAR filed.' AS DECISION_NOTES,
    DATEADD('minute', -1 * (180 + MOD(SEQ4(), 90)), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('minute', -1 * (120 + MOD(SEQ4(), 60)), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('minute', -1 * (30 + MOD(SEQ4(), 90)), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 70));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE, SAR_FILED_TIMESTAMP,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_' || LPAD(SEQ4()::VARCHAR, 5, '0') AS DECISION_ID,
    'FRAUD_ALT_' || LPAD(MOD(SEQ4(), 60)::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_TXN_' || LPAD(MOD(SEQ4(), 300)::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD(MOD(SEQ4(), 50)::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DECISION,
    TRUE AS SAR_RECOMMENDED,
    TRUE AS SAR_FILED,
    CURRENT_DATE() - MOD(SEQ4(), 7) AS SAR_FILED_DATE,
    DATEADD('hour', -1 * MOD(SEQ4(), 48), CURRENT_TIMESTAMP()) AS SAR_FILED_TIMESTAMP,
    ROUND(0.88 + UNIFORM(0, 0.12, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'CONFIRM_FRAUD' AS AGENT_RECOMMENDATION,
    'HIGH' AS AGENT_CONFIDENCE,
    'Bust-out pattern detected: Customer utilization ratio exceeded 95% with rapid sequential transactions totaling $' || (5000 + MOD(SEQ4() * 137, 15000))::VARCHAR || ' within 24 hours. ML model probability ' || ROUND(0.88 + UNIFORM(0, 0.12, RANDOM())::NUMBER(5,4), 4)::VARCHAR || ' exceeds SAR threshold. Historical pattern matches known bust-out lifecycle phase 3 (bust phase).' AS AGENT_REASONING_SUMMARY,
    'BUST_OUT_PATTERN' AS RULE_TRIGGERED,
    TRUE AS RULE_ML_AGREEMENT,
    TRUE AS SAR_THRESHOLD_MET,
    'HIGH' AS CONFIDENCE_LEVEL,
    'Agent AI and ML model agree on bust-out fraud confirmation. SAR filed per FinCEN >$5K threshold.' AS DECISION_NOTES,
    DATEADD('minute', -1 * (120 + MOD(SEQ4(), 60)), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('minute', -1 * (60 + MOD(SEQ4(), 60)), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('minute', -1 * MOD(SEQ4(), 60), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 70));


INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE, SAR_FILED_TIMESTAMP,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_' || LPAD((210 + SEQ4())::VARCHAR, 5, '0') AS DECISION_ID,
    'FRAUD_ALT_' || LPAD((180 + MOD(SEQ4(), 60))::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_TXN_' || LPAD((900 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DECISION,
    TRUE AS SAR_RECOMMENDED,
    TRUE AS SAR_FILED,
    CURRENT_DATE() - MOD(SEQ4(), 3) AS SAR_FILED_DATE,
    DATEADD('hour', -1 * MOD(SEQ4(), 36), CURRENT_TIMESTAMP()) AS SAR_FILED_TIMESTAMP,
    ROUND(0.89 + UNIFORM(0, 0.11, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'CONFIRM_FRAUD' AS AGENT_RECOMMENDATION,
    'HIGH' AS AGENT_CONFIDENCE,
    'Account takeover confirmed: ' || (5 + MOD(SEQ4(), 12))::VARCHAR || ' transactions in 1 hour from new device (DEV_ATO_' || MOD(SEQ4(), 5)::VARCHAR || '), total amount $' || (5000 + MOD(SEQ4() * 233, 15000))::VARCHAR || '. Velocity 10x above customer baseline. Geographic anomaly: login from ' || CASE MOD(SEQ4(), 3) WHEN 0 THEN 'Russia' WHEN 1 THEN 'China' ELSE 'Brazil' END || ' while customer is US-based. ML probability >0.90 confirms ATO pattern.' AS AGENT_REASONING_SUMMARY,
    'VELOCITY_CHECK' AS RULE_TRIGGERED,
    TRUE AS RULE_ML_AGREEMENT,
    TRUE AS SAR_THRESHOLD_MET,
    'HIGH' AS CONFIDENCE_LEVEL,
    'Account takeover. Rule + ML + Agent all confirm. SAR filed for aggregated amount >$5K.' AS DECISION_NOTES,
    DATEADD('minute', -1 * (90 + MOD(SEQ4(), 30)), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('minute', -1 * (60 + MOD(SEQ4(), 30)), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('minute', -1 * MOD(SEQ4(), 30), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 70));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE, SAR_FILED_TIMESTAMP,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_' || LPAD((140 + SEQ4())::VARCHAR, 5, '0') AS DECISION_ID,
    'FRAUD_ALT_' || LPAD((120 + MOD(SEQ4(), 60))::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_TXN_' || LPAD((600 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((100 + MOD(SEQ4(), 40))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DECISION,
    TRUE AS SAR_RECOMMENDED,
    TRUE AS SAR_FILED,
    CURRENT_DATE() - MOD(SEQ4(), 5) AS SAR_FILED_DATE,
    DATEADD('hour', -1 * (12 + MOD(SEQ4(), 48)), CURRENT_TIMESTAMP()) AS SAR_FILED_TIMESTAMP,
    ROUND(0.83 + UNIFORM(0, 0.17, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'ESCALATE_SAR' AS AGENT_RECOMMENDATION,
    'HIGH' AS AGENT_CONFIDENCE,
    'Large cash advance of $' || (8000 + MOD(SEQ4() * 179, 12000))::VARCHAR || ' detected at ATM. Single transaction exceeds FinCEN $5,000 SAR reporting threshold. Customer has no prior cash advance history, account age <90 days. ML model confirms anomalous behavior. Agent recommends immediate SAR escalation per regulatory requirement (30-day filing window).' AS AGENT_REASONING_SUMMARY,
    'LARGE_CASH_ADVANCE' AS RULE_TRIGGERED,
    TRUE AS RULE_ML_AGREEMENT,
    TRUE AS SAR_THRESHOLD_MET,
    'HIGH' AS CONFIDENCE_LEVEL,
    'SAR filed within 24 hours. Single txn >$5K triggers mandatory reporting. Agent + ML concur.' AS DECISION_NOTES,
    DATEADD('minute', -1 * (150 + MOD(SEQ4(), 60)), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('minute', -1 * (90 + MOD(SEQ4(), 60)), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('minute', -1 * (20 + MOD(SEQ4(), 60)), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 70));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE, SAR_FILED_TIMESTAMP,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_' || LPAD((330 + SEQ4())::VARCHAR, 5, '0') AS DECISION_ID,
    'FRAUD_ALT_' || LPAD((240 + MOD(SEQ4(), 60))::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_TXN_' || LPAD((1200 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((170 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DECISION,
    TRUE AS SAR_RECOMMENDED,
    TRUE AS SAR_FILED,
    CURRENT_DATE() - MOD(SEQ4(), 3) AS SAR_FILED_DATE,
    DATEADD('hour', -1 * MOD(SEQ4(), 24), CURRENT_TIMESTAMP()) AS SAR_FILED_TIMESTAMP,
    ROUND(0.78 + UNIFORM(0, 0.22, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'CONFIRM_FRAUD' AS AGENT_RECOMMENDATION,
    'MEDIUM' AS AGENT_CONFIDENCE,
    'ML model detected anomaly (score >0.78) without specific rule trigger. LLM reasoning identified cross-pattern indicators: high-risk country merchant (' || CASE MOD(SEQ4(), 3) WHEN 0 THEN 'Nigeria' WHEN 1 THEN 'Iran' ELSE 'North Korea' END || ') combined with new device fingerprint and unusual transaction time (3AM local). Individual signals below rule thresholds but combined probability indicates fraud. Agent recommends investigation escalation.' AS AGENT_REASONING_SUMMARY,
    NULL AS RULE_TRIGGERED,
    FALSE AS RULE_ML_AGREEMENT,
    TRUE AS SAR_THRESHOLD_MET,
    'MEDIUM' AS CONFIDENCE_LEVEL,
    'No rule fired but ML + Agent LLM reasoning identified fraud. Model learning gap — new pattern for retraining.' AS DECISION_NOTES,
    DATEADD('minute', -1 * (100 + MOD(SEQ4(), 40)), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('minute', -1 * (60 + MOD(SEQ4(), 40)), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('minute', -1 * (10 + MOD(SEQ4(), 30)), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 20));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE, SAR_FILED_TIMESTAMP,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_' || LPAD((280 + SEQ4())::VARCHAR, 5, '0') AS DECISION_ID,
    'ALT' || LPAD((100 + MOD(SEQ4() * 3, 700))::VARCHAR, 6, '0') AS ALERT_ID,
    NULL AS TRANSACTION_ID,
    'CUST' || LPAD(MOD(SEQ4() * 7, 728)::VARCHAR, 5, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'FALSE_POSITIVE' AS DECISION,
    FALSE AS SAR_RECOMMENDED,
    FALSE AS SAR_FILED,
    NULL AS SAR_FILED_DATE,
    NULL AS SAR_FILED_TIMESTAMP,
    ROUND(0.05 + UNIFORM(0, 0.25, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'FALSE_POSITIVE' AS AGENT_RECOMMENDATION,
    'HIGH' AS AGENT_CONFIDENCE,
    'Alert triggered by ' || CASE MOD(SEQ4(), 3) WHEN 0 THEN 'HIGH_RISK_COUNTRY rule but customer is known frequent international traveler.' WHEN 1 THEN 'VELOCITY_CHECK but transaction pattern consistent with regular business activity.' ELSE 'ADDRESS_MISMATCH but customer recently relocated (confirmed via CRM update).' END || ' ML score < 0.3 indicates low fraud probability. No suspicious indicators found in transaction history or velocity patterns.' AS AGENT_REASONING_SUMMARY,
    CASE MOD(SEQ4(), 3) WHEN 0 THEN 'HIGH_RISK_COUNTRY' WHEN 1 THEN 'VELOCITY_CHECK' ELSE 'ADDRESS_MISMATCH' END AS RULE_TRIGGERED,
    TRUE AS RULE_ML_AGREEMENT,
    FALSE AS SAR_THRESHOLD_MET,
    'HIGH' AS CONFIDENCE_LEVEL,
    'False positive confirmed. Rule fired but ML + Agent reasoning both indicate legitimate activity.' AS DECISION_NOTES,
    DATEADD('minute', -1 * (200 + MOD(SEQ4(), 100)), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('minute', -1 * (140 + MOD(SEQ4(), 60)), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('minute', -1 * (60 + MOD(SEQ4(), 120)), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 50));

UPDATE DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS
SET DISPOSITION = 'CONFIRMED_FRAUD',
    SAR_FILED = TRUE,
    ALERT_STATUS = 'CLOSED_CONFIRMED'
WHERE ALERT_STATUS = 'ESCALATED'
  AND SOURCE_SYSTEM = 'DETECTION_ENGINE'
  AND RULE_CODE IN ('BUST_OUT_PATTERN', 'DEVICE_ANOMALY', 'SSN_VELOCITY', 'LARGE_CASH_ADVANCE', 'LINKED_ACCOUNT_RISK', 'MERGER_IDENTITY_GAP');

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD((240 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD((170 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 168), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    CASE MOD(SEQ4(), 2) WHEN 0 THEN 'HIGH_RISK_COUNTRY' ELSE 'DEVICE_ANOMALY' END AS RULE_CODE,
    CASE MOD(SEQ4(), 2)
        WHEN 0 THEN 'Rule Code: HIGH_RISK_COUNTRY — Detection Logic and Thresholds'
        ELSE 'Rule Code: DEVICE_ANOMALY — Detection Logic and Thresholds'
    END AS RULE_DESCRIPTION,
    ROUND(0.82 + UNIFORM(0, 0.18, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD((1200 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((1200 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((170 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((170 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 168), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(3000 + UNIFORM(0, 17000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'TRANSFER'
        WHEN 1 THEN 'PURCHASE'
        ELSE 'WITHDRAWAL'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'JEWELRY'
        WHEN 1 THEN 'CRYPTO'
        WHEN 2 THEN 'ELECTRONICS'
        ELSE 'TRAVEL'
    END AS MERCHANT_CATEGORY,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'MOBILE'
        ELSE 'ATM'
    END AS CHANNEL,
    'INTL_MERCHANT_' || MOD(SEQ4(), 15)::VARCHAR AS MERCHANT_NAME,
    CASE MOD(SEQ4(), 6)
        WHEN 0 THEN 'NG'
        WHEN 1 THEN 'RU'
        WHEN 2 THEN 'IR'
        WHEN 3 THEN 'KP'
        WHEN 4 THEN 'MM'
        ELSE 'AF'
    END AS MERCHANT_COUNTRY,
    'DEV_INTL_' || MOD(SEQ4(), 20)::VARCHAR AS DEVICE_ID,
    '10.0.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD(SEQ4()::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD(MOD(SEQ4(), 50)::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD(MOD(SEQ4(), 50)::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 1440), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(5000 + UNIFORM(0, 15000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'PURCHASE'
        WHEN 1 THEN 'TRANSFER'
        WHEN 2 THEN 'CASH_ADVANCE'
        ELSE 'WITHDRAWAL'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'ELECTRONICS'
        WHEN 2 THEN 'JEWELRY'
        WHEN 3 THEN 'TRAVEL'
        ELSE 'CRYPTO'
    END AS MERCHANT_CATEGORY,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'ATM'
        ELSE 'MOBILE'
    END AS CHANNEL,
    'MERCHANT_FRAUD_' || MOD(SEQ4(), 20)::VARCHAR AS MERCHANT_NAME,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'NG'
        WHEN 1 THEN 'RU'
        WHEN 2 THEN 'CN'
        WHEN 3 THEN 'IR'
        ELSE 'US'
    END AS MERCHANT_COUNTRY,
    'DEV_FRAUD_' || MOD(SEQ4(), 30)::VARCHAR AS DEVICE_ID,
    '192.168.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));


INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((900 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 72), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(5000 + UNIFORM(0, 20000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    'CASH_ADVANCE' AS TRANSACTION_TYPE,
    'ATM' AS MERCHANT_CATEGORY,
    'ATM' AS CHANNEL,
    'ATM_LOCATION_' || MOD(SEQ4(), 20)::VARCHAR AS MERCHANT_NAME,
    'US' AS MERCHANT_COUNTRY,
    'ATM_DEV_' || MOD(SEQ4(), 15)::VARCHAR AS DEVICE_ID,
    NULL AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((300 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((50 + MOD(SEQ4(), 50))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((50 + MOD(SEQ4(), 50))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 2880), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(2000 + UNIFORM(0, 8000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'PURCHASE'
        WHEN 1 THEN 'TRANSFER'
        ELSE 'CASH_ADVANCE'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 4)
        WHEN 0 THEN 'ELECTRONICS'
        WHEN 1 THEN 'ONLINE'
        WHEN 2 THEN 'RETAIL'
        ELSE 'GAS'
    END AS MERCHANT_CATEGORY,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'MOBILE'
        ELSE 'ATM'
    END AS CHANNEL,
    'SYNTH_MERCHANT_' || MOD(SEQ4(), 25)::VARCHAR AS MERCHANT_NAME,
    'US' AS MERCHANT_COUNTRY,
    'DEV_SYNTH_' || MOD(SEQ4(), 10)::VARCHAR AS DEVICE_ID,
    '172.16.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID, CUSTOMER_ID, ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT,
    TRANSACTION_TYPE, MERCHANT_CATEGORY, CHANNEL, MERCHANT_NAME, MERCHANT_COUNTRY,
    DEVICE_ID, IP_ADDRESS, SOURCE_SYSTEM
)
SELECT
    'FRAUD_TXN_' || LPAD((600 + SEQ4())::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((100 + MOD(SEQ4(), 40))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'FRAUD_ACC_' || LPAD((100 + MOD(SEQ4(), 40))::VARCHAR, 4, '0') AS ACCOUNT_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 60), CURRENT_TIMESTAMP()) AS TRANSACTION_DATE,
    ROUND(1000 + UNIFORM(0, 9000, RANDOM())::NUMBER(10,2), 2) AS TRANSACTION_AMOUNT,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'PURCHASE'
        WHEN 1 THEN 'TRANSFER'
        ELSE 'WITHDRAWAL'
    END AS TRANSACTION_TYPE,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'ONLINE'
        WHEN 1 THEN 'ELECTRONICS'
        WHEN 2 THEN 'TRAVEL'
        WHEN 3 THEN 'CRYPTO'
        ELSE 'RETAIL'
    END AS MERCHANT_CATEGORY,
    'ONLINE' AS CHANNEL,
    'ATO_MERCHANT_' || MOD(SEQ4(), 30)::VARCHAR AS MERCHANT_NAME,
    'US' AS MERCHANT_COUNTRY,
    'NEW_DEVICE_' || MOD(SEQ4(), 5)::VARCHAR AS DEVICE_ID,
    '10.10.' || MOD(SEQ4(), 255)::VARCHAR || '.' || MOD(SEQ4(), 255)::VARCHAR AS IP_ADDRESS,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));


INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_VELOCITY_EVENTS (
    EVENT_ID, CUSTOMER_ID, EVENT_TIMESTAMP, TXN_COUNT_1H, TXN_COUNT_24H,
    TXN_AMOUNT_1H, TXN_AMOUNT_24H, DISTINCT_MERCHANTS_24H,
    RECENT_TXN_COUNT, RECENT_TXN_AMOUNT, FRAUD_RATE_7D, SOURCE_SYSTEM
)
SELECT
    'FRAUD_EVT_' || LPAD(SEQ4()::VARCHAR, 5, '0') AS EVENT_ID,
    'FRAUD_CUST_' || LPAD(MOD(SEQ4(), 200)::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('minute', -1 * MOD(SEQ4(), 1440), CURRENT_TIMESTAMP()) AS EVENT_TIMESTAMP,
    5 + MOD(SEQ4(), 15) AS TXN_COUNT_1H,
    15 + MOD(SEQ4(), 40) AS TXN_COUNT_24H,
    ROUND(3000 + UNIFORM(0, 12000, RANDOM())::NUMBER(10,2), 2) AS TXN_AMOUNT_1H,
    ROUND(8000 + UNIFORM(0, 30000, RANDOM())::NUMBER(10,2), 2) AS TXN_AMOUNT_24H,
    5 + MOD(SEQ4(), 10) AS DISTINCT_MERCHANTS_24H,
    10 + MOD(SEQ4(), 20) AS RECENT_TXN_COUNT,
    ROUND(5000 + UNIFORM(0, 20000, RANDOM())::NUMBER(10,2), 2) AS RECENT_TXN_AMOUNT,
    ROUND(0.15 + UNIFORM(0, 0.85, RANDOM())::NUMBER(8,6), 6) AS FRAUD_RATE_7D,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 300));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_CUSTOMERS (
    CUSTOMER_ID, FULL_NAME, DATE_OF_BIRTH, SSN_LAST_FOUR, EMAIL, PHONE,
    ADDRESS_LINE_1, CITY, STATE, ZIP_CODE, COUNTRY,
    RISK_SEGMENT, KYC_COMPLETE, IS_SYNTHETIC_FLAG, IS_MERGER_DUP_FLAG,
    CUSTOMER_SINCE, ACCOUNT_COUNT, SOURCE_SYSTEM
)
SELECT
    'FRAUD_CUST_' || LPAD(SEQ4()::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'Synthetic Person ' || SEQ4()::VARCHAR AS FULL_NAME,
    DATEADD('year', -1 * (20 + MOD(SEQ4(), 40)), CURRENT_DATE()) AS DATE_OF_BIRTH,
    LPAD(MOD(SEQ4() * 7919, 10000)::VARCHAR, 4, '0') AS SSN_LAST_FOUR,
    'fraud_user_' || SEQ4()::VARCHAR || '@tempmail.com' AS EMAIL,
    '555-' || LPAD(MOD(SEQ4(), 10000)::VARCHAR, 4, '0') AS PHONE,
    SEQ4()::VARCHAR || ' Fake Street' AS ADDRESS_LINE_1,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'Miami'
        WHEN 1 THEN 'Las Vegas'
        WHEN 2 THEN 'New York'
        WHEN 3 THEN 'Houston'
        ELSE 'Los Angeles'
    END AS CITY,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'FL'
        WHEN 1 THEN 'NV'
        WHEN 2 THEN 'NY'
        WHEN 3 THEN 'TX'
        ELSE 'CA'
    END AS STATE,
    LPAD(MOD(SEQ4() * 31, 100000)::VARCHAR, 5, '0') AS ZIP_CODE,
    'US' AS COUNTRY,
    'HIGH' AS RISK_SEGMENT,
    CASE WHEN MOD(SEQ4(), 3) = 0 THEN FALSE ELSE TRUE END AS KYC_COMPLETE,
    CASE WHEN MOD(SEQ4(), 2) = 0 THEN TRUE ELSE FALSE END AS IS_SYNTHETIC_FLAG,
    CASE WHEN MOD(SEQ4(), 10) = 0 THEN TRUE ELSE FALSE END AS IS_MERGER_DUP_FLAG,
    DATEADD('day', -1 * MOD(SEQ4(), 60), CURRENT_DATE()) AS CUSTOMER_SINCE,
    1 + MOD(SEQ4(), 3) AS ACCOUNT_COUNT,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 200));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD((180 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD((140 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 72), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    'LARGE_CASH_ADVANCE' AS RULE_CODE,
    'Rule Code: LARGE_CASH_ADVANCE — Detection Logic and Thresholds' AS RULE_DESCRIPTION,
    ROUND(0.80 + UNIFORM(0, 0.20, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD((900 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));


INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD(SEQ4()::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD(MOD(SEQ4(), 50)::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 168), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    'BUST_OUT_PATTERN' AS RULE_CODE,
    'Rule Code: BUST_OUT_PATTERN — Detection Logic and Thresholds' AS RULE_DESCRIPTION,
    ROUND(0.85 + UNIFORM(0, 0.15, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD(MOD(SEQ4(), 300)::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));


INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD((60 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD((50 + MOD(SEQ4(), 50))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 336), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    CASE MOD(SEQ4(), 2) WHEN 0 THEN 'SSN_VELOCITY' ELSE 'DEVICE_ANOMALY' END AS RULE_CODE,
    CASE MOD(SEQ4(), 2)
        WHEN 0 THEN 'Rule Code: SSN_VELOCITY — Detection Logic and Thresholds'
        ELSE 'Rule Code: DEVICE_ANOMALY — Detection Logic and Thresholds'
    END AS RULE_DESCRIPTION,
    ROUND(0.82 + UNIFORM(0, 0.18, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD((300 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));


INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD((120 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD((100 + MOD(SEQ4(), 40))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 48), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    'VELOCITY_CHECK' AS RULE_CODE,
    'Rule Code: VELOCITY_CHECK — Detection Logic and Thresholds' AS RULE_DESCRIPTION,
    ROUND(0.88 + UNIFORM(0, 0.12, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD((600 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));


UPDATE DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS
SET DISPOSITION = 'CONFIRMED_FRAUD',
    SAR_FILED = TRUE,
    ALERT_STATUS = 'CLOSED_CONFIRMED'
WHERE ALERT_STATUS = 'ESCALATED'
  AND SOURCE_SYSTEM = 'DETECTION_ENGINE'
  AND RULE_CODE IN ('BUST_OUT_PATTERN', 'DEVICE_ANOMALY', 'SSN_VELOCITY', 'LARGE_CASH_ADVANCE', 'LINKED_ACCOUNT_RISK', 'MERGER_IDENTITY_GAP');

  
INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_RAW_ALERTS (
    ALERT_ID, CUSTOMER_ID, ALERT_DATE, RULE_CODE, RULE_DESCRIPTION,
    ALERT_RISK_SCORE, ALERT_STATUS, ANALYST_ID, DISPOSITION, SAR_FILED,
    TRANSACTION_ID, SOURCE_SYSTEM
)
SELECT
    'FRAUD_ALT_' || LPAD((240 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_CUST_' || LPAD((170 + MOD(SEQ4(), 30))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    DATEADD('hour', -1 * MOD(SEQ4(), 168), CURRENT_TIMESTAMP()) AS ALERT_DATE,
    CASE MOD(SEQ4(), 2) WHEN 0 THEN 'HIGH_RISK_COUNTRY' ELSE 'DEVICE_ANOMALY' END AS RULE_CODE,
    CASE MOD(SEQ4(), 2)
        WHEN 0 THEN 'Rule Code: HIGH_RISK_COUNTRY — Detection Logic and Thresholds'
        ELSE 'Rule Code: DEVICE_ANOMALY — Detection Logic and Thresholds'
    END AS RULE_DESCRIPTION,
    ROUND(0.82 + UNIFORM(0, 0.18, RANDOM())::NUMBER(5,2), 2) AS ALERT_RISK_SCORE,
    'CLOSED_CONFIRMED' AS ALERT_STATUS,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DISPOSITION,
    TRUE AS SAR_FILED,
    'FRAUD_TXN_' || LPAD((1200 + MOD(SEQ4(), 300))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'SYNTHETIC_FRAUD_LOAD' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 60));


INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_' || LPAD(SEQ4()::VARCHAR, 5, '0') AS DECISION_ID,
    'FRAUD_ALT_' || LPAD(MOD(SEQ4(), 300)::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_TXN_' || LPAD(MOD(SEQ4(), 1500)::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD(MOD(SEQ4(), 200)::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DECISION,
    TRUE AS SAR_RECOMMENDED,
    TRUE AS SAR_FILED,
    DATEADD('day', -1 * MOD(SEQ4(), 14), CURRENT_DATE()) AS SAR_FILED_DATE,
    ROUND(0.82 + UNIFORM(0, 0.18, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'CONFIRM_FRAUD' AS AGENT_RECOMMENDATION,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'HIGH'
        WHEN 1 THEN 'HIGH'
        ELSE 'MEDIUM'
    END AS AGENT_CONFIDENCE,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'ML model scored 0.92 fraud probability. Bust-out pattern detected: utilization ratio exceeded 0.95 with rapid transaction acceleration over 24h. Rule BUST_OUT_PATTERN triggered. SAR threshold met with aggregated amount $15,234. Recommend immediate SAR filing.'
        WHEN 1 THEN 'Synthetic identity markers detected: new account (<30 days), SSN velocity anomaly across 3 linked accounts. ML score 0.88. Agent confirms high fraud confidence. FinCEN SAR required - aggregated suspicious activity exceeds $5,000 threshold.'
        WHEN 2 THEN 'Account takeover indicators: 12 transactions in 1 hour from new device, 8 distinct merchants in 24h. ML probability 0.91. Velocity check rule triggered. Total suspicious amount $23,450 exceeds SAR threshold. Recommend SAR with 5-W narrative.'
        WHEN 3 THEN 'Large cash advance pattern: single ATM withdrawal $8,500 exceeding normal customer behavior by 4 standard deviations. ML score 0.85. LARGE_CASH_ADVANCE rule fired. Amount exceeds $5,000 SAR threshold. Filing recommended within 30 days.'
        ELSE 'Device anomaly combined with high-risk country transactions. ML probability 0.87. Multiple rule triggers: DEVICE_ANOMALY + HIGH_RISK_COUNTRY. Aggregate suspicious transactions total $12,800. SAR filing mandated per FinCEN guidelines.'
    END AS AGENT_REASONING_SUMMARY,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 'BUST_OUT_PATTERN'
        WHEN 1 THEN 'SSN_VELOCITY'
        WHEN 2 THEN 'VELOCITY_CHECK'
        WHEN 3 THEN 'LARGE_CASH_ADVANCE'
        ELSE 'DEVICE_ANOMALY'
    END AS RULE_TRIGGERED,
    TRUE AS RULE_ML_AGREEMENT,
    TRUE AS SAR_THRESHOLD_MET,
    CASE MOD(SEQ4(), 3) WHEN 0 THEN 'HIGH' WHEN 1 THEN 'HIGH' ELSE 'MEDIUM' END AS CONFIDENCE_LEVEL,
    'Agent-assisted triage confirmed fraud. ML model and rule-based engine in agreement. SAR filed per FinCEN requirements.' AS DECISION_NOTES,
    DATEADD('minute', -1 * (30 + MOD(SEQ4(), 120)), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('minute', -1 * (25 + MOD(SEQ4(), 120)), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('minute', -1 * (10 + MOD(SEQ4(), 120)), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 280));


  INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_FP_' || LPAD(SEQ4()::VARCHAR, 4, '0') AS DECISION_ID,
    'ALT' || LPAD((100 + MOD(SEQ4(), 155))::VARCHAR, 6, '0') AS ALERT_ID,
    NULL AS TRANSACTION_ID,
    'CUST' || LPAD((MOD(SEQ4(), 728))::VARCHAR, 5, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'FALSE_POSITIVE' AS DECISION,
    FALSE AS SAR_RECOMMENDED,
    FALSE AS SAR_FILED,
    NULL AS SAR_FILED_DATE,
    ROUND(0.05 + UNIFORM(0, 0.20, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'FALSE_POSITIVE' AS AGENT_RECOMMENDATION,
    'HIGH' AS AGENT_CONFIDENCE,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'ML model scored low fraud probability (0.12). Alert triggered by HIGH_RISK_COUNTRY rule but customer has documented travel history. No velocity anomalies. Agent recommends closure as false positive.'
        WHEN 1 THEN 'Low ML score (0.08). NEW_ACCOUNT_SPIKE rule triggered but customer is legitimate new account with proper KYC documentation. No suspicious patterns detected. Recommend close as false positive.'
        ELSE 'ML probability 0.15. VELOCITY_CHECK triggered by legitimate payroll processing. Customer is business account with known high-volume pattern. No SAR indicators present.'
    END AS AGENT_REASONING_SUMMARY,
    CASE MOD(SEQ4(), 3)
        WHEN 0 THEN 'HIGH_RISK_COUNTRY'
        WHEN 1 THEN 'NEW_ACCOUNT_SPIKE'
        ELSE 'VELOCITY_CHECK'
    END AS RULE_TRIGGERED,
    TRUE AS RULE_ML_AGREEMENT,
    FALSE AS SAR_THRESHOLD_MET,
    'HIGH' AS CONFIDENCE_LEVEL,
    'Agent and ML model agree: false positive. No SAR required.' AS DECISION_NOTES,
    DATEADD('hour', -1 * MOD(SEQ4(), 72), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('hour', -1 * MOD(SEQ4(), 72), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('hour', -1 * MOD(SEQ4(), 72), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 50));

INSERT INTO DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID, ALERT_ID, TRANSACTION_ID, CUSTOMER_ID, ANALYST_ID,
    DECISION, SAR_RECOMMENDED, SAR_FILED, SAR_FILED_DATE,
    ML_SCORE_AT_DECISION, AGENT_RECOMMENDATION, AGENT_CONFIDENCE,
    AGENT_REASONING_SUMMARY, RULE_TRIGGERED, RULE_ML_AGREEMENT,
    SAR_THRESHOLD_MET, CONFIDENCE_LEVEL, DECISION_NOTES,
    AGENT_SCORED_AT, AGENT_REASONED_AT, DECISION_TIMESTAMP, SOURCE_SYSTEM
)
SELECT
    'DEC_MLCATCH_' || LPAD(SEQ4()::VARCHAR, 3, '0') AS DECISION_ID,
    'FRAUD_ALT_' || LPAD((280 + SEQ4())::VARCHAR, 5, '0') AS ALERT_ID,
    'FRAUD_TXN_' || LPAD((1400 + MOD(SEQ4(), 100))::VARCHAR, 5, '0') AS TRANSACTION_ID,
    'FRAUD_CUST_' || LPAD((180 + MOD(SEQ4(), 20))::VARCHAR, 4, '0') AS CUSTOMER_ID,
    'ANALYST0' || (1 + MOD(SEQ4(), 8))::VARCHAR AS ANALYST_ID,
    'CONFIRMED_FRAUD' AS DECISION,
    TRUE AS SAR_RECOMMENDED,
    TRUE AS SAR_FILED,
    DATEADD('day', -1 * MOD(SEQ4(), 7), CURRENT_DATE()) AS SAR_FILED_DATE,
    ROUND(0.75 + UNIFORM(0, 0.20, RANDOM())::NUMBER(5,4), 4) AS ML_SCORE_AT_DECISION,
    'CONFIRM_FRAUD' AS AGENT_RECOMMENDATION,
    'MEDIUM' AS AGENT_CONFIDENCE,
    'No rule triggered for this alert. However, ML model detected anomalous pattern (score 0.78+). Agent LLM reasoning identified correlation: transaction amount just below $5K threshold (structuring behavior), combined with new device and rapid account activity. Pattern consistent with layering/structuring to avoid CTR. SAR recommended based on ML + behavioral analysis.' AS AGENT_REASONING_SUMMARY,
    NULL AS RULE_TRIGGERED,
    FALSE AS RULE_ML_AGREEMENT,
    TRUE AS SAR_THRESHOLD_MET,
    'MEDIUM' AS CONFIDENCE_LEVEL,
    'ML model caught fraud that rule-based engine missed. Structuring pattern below individual thresholds but aggregated exceeds $5K. Agent reasoning confirmed.' AS DECISION_NOTES,
    DATEADD('hour', -1 * MOD(SEQ4(), 48), CURRENT_TIMESTAMP()) AS AGENT_SCORED_AT,
    DATEADD('hour', -1 * MOD(SEQ4(), 48), CURRENT_TIMESTAMP()) AS AGENT_REASONED_AT,
    DATEADD('hour', -1 * MOD(SEQ4(), 48), CURRENT_TIMESTAMP()) AS DECISION_TIMESTAMP,
    'AGENT_ASSISTED_TRIAGE' AS SOURCE_SYSTEM
FROM TABLE(GENERATOR(ROWCOUNT => 20));









