USE ROLE SYSADMIN;


SELECT 'OPS_DATA_MODALITY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM ADMIN_DB.OPS.OPS_DATA_MODALITY
UNION ALL
SELECT 'OPS_VARIANT_RICHNESS', COUNT(*) FROM ADMIN_DB.OPS.OPS_VARIANT_RICHNESS
UNION ALL
SELECT 'OPS_DQ_AUDIT_SUMMARY', COUNT(*) FROM ADMIN_DB.OPS.OPS_DQ_AUDIT_SUMMARY
UNION ALL
SELECT 'OPS_ML_EVALUATION', COUNT(*) FROM ADMIN_DB.OPS.OPS_ML_EVALUATION
UNION ALL
SELECT 'OPS_ML_INFERENCE', COUNT(*) FROM ADMIN_DB.OPS.OPS_ML_INFERENCE
UNION ALL
SELECT 'OPS_AGENT_COST', COUNT(*) FROM ADMIN_DB.OPS.OPS_AGENT_COST
UNION ALL
SELECT 'OPS_AI_FUNCTION_USAGE', COUNT(*) FROM ADMIN_DB.OPS.OPS_AI_FUNCTION_USAGE
UNION ALL
SELECT 'OPS_DAILY_AI_SPEND', COUNT(*) FROM ADMIN_DB.OPS.OPS_DAILY_AI_SPEND
ORDER BY TABLE_NAME;
