-- =============================================================================
-- SBR Intelligence Platform - Infrastructure Setup
-- Database, Schema, Warehouse, Roles, and Grants
-- =============================================================================

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS DEMO_DEV;
CREATE SCHEMA IF NOT EXISTS DEMO_DEV.SBR_ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS SBR_ANALYTICS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS SBR_ANALYTICS_ROLE;
GRANT ROLE SBR_ANALYTICS_ROLE TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE DEMO_DEV TO ROLE SBR_ANALYTICS_ROLE;
GRANT USAGE ON SCHEMA DEMO_DEV.SBR_ANALYTICS TO ROLE SBR_ANALYTICS_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DEMO_DEV.SBR_ANALYTICS TO ROLE SBR_ANALYTICS_ROLE;
GRANT USAGE ON WAREHOUSE SBR_ANALYTICS_WH TO ROLE SBR_ANALYTICS_ROLE;
GRANT CREATE TABLE ON SCHEMA DEMO_DEV.SBR_ANALYTICS TO ROLE SBR_ANALYTICS_ROLE;
GRANT CREATE VIEW ON SCHEMA DEMO_DEV.SBR_ANALYTICS TO ROLE SBR_ANALYTICS_ROLE;
GRANT CREATE STAGE ON SCHEMA DEMO_DEV.SBR_ANALYTICS TO ROLE SBR_ANALYTICS_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA DEMO_DEV.SBR_ANALYTICS TO ROLE SBR_ANALYTICS_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA DEMO_DEV.SBR_ANALYTICS TO ROLE SBR_ANALYTICS_ROLE;
