-- =============================================================================
-- SBR Intelligence Platform - Stored Procedures
-- =============================================================================

USE ROLE SBR_ANALYTICS_ROLE;
USE SCHEMA DEMO_DEV.SBR_ANALYTICS;

-- -----------------------------------------------------------------------------
-- SBR_CREATE_CASE: Creates a new investigation case
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SBR_CREATE_CASE(P_EMP_ID VARCHAR, P_PERIOD_START DATE, P_PERIOD_END DATE, P_SEVERITY VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_CASE_ID VARCHAR;
    V_USER VARCHAR;
    V_ROLE VARCHAR;
    V_PAYLOAD VARCHAR;
BEGIN
    V_CASE_ID := UUID_STRING();
    V_USER := CURRENT_USER();
    V_ROLE := CURRENT_ROLE();
    V_PAYLOAD := '{"emp_id":"' || :P_EMP_ID || '","severity":"' || :P_SEVERITY || '"}';
    INSERT INTO DEMO_DEV.SBR_ANALYTICS.GOLD_APP_SBR_CASES (CASE_ID, EMP_ID, PERIOD_START, PERIOD_END, STATUS, SEVERITY, CREATED_BY, UPDATED_BY)
    VALUES (:V_CASE_ID, :P_EMP_ID, :P_PERIOD_START, :P_PERIOD_END, 'OPEN', :P_SEVERITY, :V_USER, :V_USER);
    INSERT INTO DEMO_DEV.SBR_ANALYTICS.GOLD_APP_SBR_CASE_EVENTS (CASE_ID, EVENT_TYPE, USER_NAME, USER_ROLE, PAYLOAD)
    SELECT :V_CASE_ID, 'CREATE_CASE', :V_USER, :V_ROLE, PARSE_JSON(:V_PAYLOAD);
    RETURN V_CASE_ID;
END
$$;

-- -----------------------------------------------------------------------------
-- SBR_UPDATE_CASE: Updates case status and logs event
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SBR_UPDATE_CASE(P_CASE_ID VARCHAR, P_EVENT_TYPE VARCHAR, P_PAYLOAD VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_USER VARCHAR;
    V_ROLE VARCHAR;
BEGIN
    V_USER := CURRENT_USER();
    V_ROLE := CURRENT_ROLE();
    IF (:P_EVENT_TYPE = 'STATUS_CHANGE') THEN
        UPDATE DEMO_DEV.SBR_ANALYTICS.GOLD_APP_SBR_CASES
        SET STATUS = PARSE_JSON(:P_PAYLOAD):status::VARCHAR,
            UPDATED_AT = CURRENT_TIMESTAMP(),
            UPDATED_BY = :V_USER
        WHERE CASE_ID = :P_CASE_ID;
    END IF;
    INSERT INTO DEMO_DEV.SBR_ANALYTICS.GOLD_APP_SBR_CASE_EVENTS (CASE_ID, EVENT_TYPE, USER_NAME, USER_ROLE, PAYLOAD)
    SELECT :P_CASE_ID, :P_EVENT_TYPE, :V_USER, :V_ROLE, TRY_PARSE_JSON(:P_PAYLOAD);
    RETURN 'OK';
END
$$;

-- -----------------------------------------------------------------------------
-- SBR_LOG_AGENT_RUN: Logs AI agent analysis results
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SBR_LOG_AGENT_RUN(P_EMP_ID VARCHAR, P_CASE_ID VARCHAR, P_AGENT_OUTPUT VARCHAR, P_EVIDENCE_SQL VARCHAR, P_RESULT_CODE VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_RUN_ID VARCHAR;
BEGIN
    V_RUN_ID := UUID_STRING();
    INSERT INTO DEMO_DEV.SBR_ANALYTICS.GOLD_APP_SBR_AGENT_EXPLANATIONS (RUN_ID, CASE_ID, EMP_ID, RESPONSE_TS, AGENT_OUTPUT, EVIDENCE_SQL, RESULT_CODE)
    SELECT :V_RUN_ID, :P_CASE_ID, :P_EMP_ID, CURRENT_TIMESTAMP(), TRY_PARSE_JSON(:P_AGENT_OUTPUT), :P_EVIDENCE_SQL, :P_RESULT_CODE;
    RETURN V_RUN_ID;
END
$$;

-- -----------------------------------------------------------------------------
-- SBR_DETECT_SCHEMA_GAPS: Detects schema drift in vendor files
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SBR_DETECT_SCHEMA_GAPS(P_VENDOR_ID VARCHAR, P_FILE_NAME VARCHAR, P_COLUMNS_JSON VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_VENDOR_NAME VARCHAR;
BEGIN
    SELECT VENDOR_NAME INTO V_VENDOR_NAME FROM DEMO_DEV.SBR_ANALYTICS.GOLD_DIM_VENDOR WHERE VENDOR_ID = :P_VENDOR_ID;

    INSERT INTO DEMO_DEV.SBR_ANALYTICS.SILVER_VENDOR_FILE_LOG (VENDOR_ID, VENDOR_NAME, FILE_NAME, FILE_PATH, COLUMNS_FOUND, COLUMN_COUNT, ROW_COUNT, SCHEMA_MATCH_STATUS)
    SELECT :P_VENDOR_ID, :V_VENDOR_NAME, :P_FILE_NAME,
           '@SBR_SOURCE_STAGE/' || :P_VENDOR_ID || '/' || :P_FILE_NAME,
           TRY_PARSE_JSON(:P_COLUMNS_JSON), ARRAY_SIZE(TRY_PARSE_JSON(:P_COLUMNS_JSON)), 0, 'PENDING';

    INSERT INTO DEMO_DEV.SBR_ANALYTICS.SILVER_SCHEMA_GAPS (VENDOR_ID, VENDOR_NAME, FILE_NAME, GAP_TYPE, COLUMN_NAME, EXPECTED_VALUE, SEVERITY, DESCRIPTION)
    SELECT :P_VENDOR_ID, :V_VENDOR_NAME, :P_FILE_NAME, 'MISSING_COLUMN', r.COLUMN_NAME, r.COLUMN_NAME, 'HIGH',
           'Expected column ' || r.COLUMN_NAME || ' not found in file'
    FROM DEMO_DEV.SBR_ANALYTICS.SILVER_SCHEMA_REGISTRY r
    WHERE r.VENDOR_ID = :P_VENDOR_ID
      AND r.COLUMN_NAME NOT IN (SELECT VALUE::VARCHAR FROM TABLE(FLATTEN(TRY_PARSE_JSON(:P_COLUMNS_JSON))));

    RETURN 'GAPS_DETECTED';
END
$$;

-- -----------------------------------------------------------------------------
-- SBR_AUDIT_METRICS_AGENT: Runs audit metrics collection
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SBR_AUDIT_METRICS_AGENT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_TOTAL_BRZ NUMBER;
    V_TOTAL_SLV NUMBER;
    V_TOTAL_GLD NUMBER;
    V_SCHEMA_GAPS NUMBER;
    V_OPEN_CASES NUMBER;
    V_TOTAL_VARIANCE NUMBER;
    V_AUDIT_JSON VARCHAR;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL_BRZ FROM DEMO_DEV.SBR_ANALYTICS.BRONZE_LABOR;
    SELECT COUNT(*) INTO V_TOTAL_SLV FROM DEMO_DEV.SBR_ANALYTICS.SILVER_LABOR;
    SELECT COUNT(*) INTO V_TOTAL_GLD FROM DEMO_DEV.SBR_ANALYTICS.GOLD_FACT_LABOR;
    SELECT COUNT(*) INTO V_SCHEMA_GAPS FROM DEMO_DEV.SBR_ANALYTICS.SILVER_SCHEMA_GAPS WHERE STATUS = 'OPEN';
    SELECT COUNT(*) INTO V_OPEN_CASES FROM DEMO_DEV.SBR_ANALYTICS.GOLD_APP_SBR_CASES WHERE STATUS = 'OPEN';
    SELECT COALESCE(SUM(ABS(VARIANCE)), 0) INTO V_TOTAL_VARIANCE FROM DEMO_DEV.SBR_ANALYTICS.GOLD_FACT_LABOR;

    V_AUDIT_JSON := '{"bronze_records":' || :V_TOTAL_BRZ ||
                    ',"silver_records":' || :V_TOTAL_SLV ||
                    ',"gold_records":' || :V_TOTAL_GLD ||
                    ',"open_schema_gaps":' || :V_SCHEMA_GAPS ||
                    ',"open_cases":' || :V_OPEN_CASES ||
                    ',"total_abs_variance":' || :V_TOTAL_VARIANCE || '}';

    INSERT INTO DEMO_DEV.SBR_ANALYTICS.SILVER_AUDIT_METRICS (BATCH_ID, TOTAL_RECORDS, FAILED_RECORDS, TOTAL_VARIANCE)
    SELECT 'AUDIT_AGENT_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS'),
           :V_TOTAL_GLD,
           :V_TOTAL_GLD - :V_TOTAL_SLV,
           :V_TOTAL_VARIANCE;

    RETURN V_AUDIT_JSON;
END
$$;
