-- =============================================================================
-- SBR Intelligence Platform - Masking Policies
-- Data protection for PII and sensitive compensation data
-- =============================================================================

USE ROLE SBR_ANALYTICS_ROLE;
USE SCHEMA DEMO_DEV.SBR_ANALYTICS;

CREATE OR REPLACE MASKING POLICY MASK_EMP_ID AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('SBR_ANALYTICS_ROLE', 'SYSADMIN', 'ACCOUNTADMIN') THEN val
        ELSE '***-' || RIGHT(val, 2)
    END;

CREATE OR REPLACE MASKING POLICY MASK_COMPENSATION AS (val NUMBER(10,2)) RETURNS NUMBER(10,2) ->
    CASE
        WHEN CURRENT_ROLE() IN ('SBR_ANALYTICS_ROLE', 'SYSADMIN', 'ACCOUNTADMIN') THEN val
        ELSE NULL
    END;

CREATE OR REPLACE MASKING POLICY MASK_PII_TEXT AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('SBR_ANALYTICS_ROLE', 'SYSADMIN', 'ACCOUNTADMIN') THEN val
        ELSE '****'
    END;

-- Apply masking policies
ALTER TABLE GOLD_FACT_LABOR MODIFY COLUMN EMP_ID SET MASKING POLICY MASK_EMP_ID;
ALTER TABLE GOLD_FACT_LABOR MODIFY COLUMN PAY_RATE SET MASKING POLICY MASK_COMPENSATION;
ALTER TABLE GOLD_DIM_VENDOR MODIFY COLUMN CONTACT_NAME SET MASKING POLICY MASK_PII_TEXT;
ALTER TABLE GOLD_DIM_VENDOR MODIFY COLUMN CONTACT_EMAIL SET MASKING POLICY MASK_PII_TEXT;
ALTER TABLE GOLD_DIM_VENDOR MODIFY COLUMN PHONE SET MASKING POLICY MASK_PII_TEXT;
ALTER TABLE GOLD_DIM_VENDOR MODIFY COLUMN ADDRESS SET MASKING POLICY MASK_PII_TEXT;
ALTER TABLE GOLD_DIM_VENDOR MODIFY COLUMN HOURLY_RATE_MIN SET MASKING POLICY MASK_COMPENSATION;
ALTER TABLE GOLD_DIM_VENDOR MODIFY COLUMN HOURLY_RATE_MAX SET MASKING POLICY MASK_COMPENSATION;
