-- Foundational objects for model lifecycle operations.

CREATE DATABASE IF NOT EXISTS ML_PROD;
CREATE SCHEMA IF NOT EXISTS ML_PROD.MLOPS;

CREATE OR REPLACE TABLE ML_PROD.MLOPS.MODEL_REGISTRY (
    MODEL_NAME STRING NOT NULL,
    MODEL_VERSION STRING NOT NULL,
    OWNER STRING NOT NULL,
    RISK_TIER STRING NOT NULL,
    STAGE STRING NOT NULL,
    ARTIFACT_URI STRING NOT NULL,
    FEATURE_CONTRACT_VERSION STRING,
    TRAIN_DATA_WINDOW STRING,
    METRICS VARIANT,
    REGISTERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REGISTERED_BY STRING DEFAULT CURRENT_USER(),
    IS_ACTIVE BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (MODEL_NAME, MODEL_VERSION)
);

CREATE OR REPLACE TABLE ML_PROD.MLOPS.MODEL_DEPLOYMENT_EVENTS (
    EVENT_ID STRING DEFAULT UUID_STRING(),
    MODEL_NAME STRING NOT NULL,
    MODEL_VERSION STRING NOT NULL,
    ENVIRONMENT STRING NOT NULL,
    EVENT_TYPE STRING NOT NULL,
    EVENT_STATUS STRING NOT NULL,
    APPROVED_BY STRING,
    DETAILS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
