-- Lineage and approval support objects.

CREATE OR REPLACE TABLE ML_PROD.MLOPS.MODEL_LINEAGE (
    MODEL_NAME STRING NOT NULL,
    MODEL_VERSION STRING NOT NULL,
    CODE_COMMIT_SHA STRING NOT NULL,
    TRAINING_QUERY_HASH STRING,
    DATASET_VERSION STRING NOT NULL,
    FEATURE_PIPELINE_VERSION STRING,
    BUILD_ID STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MODEL_NAME, MODEL_VERSION, DATASET_VERSION)
);

CREATE OR REPLACE TABLE ML_PROD.MLOPS.MODEL_APPROVALS (
    APPROVAL_ID STRING DEFAULT UUID_STRING(),
    MODEL_NAME STRING NOT NULL,
    MODEL_VERSION STRING NOT NULL,
    ENVIRONMENT STRING NOT NULL,
    REVIEWER STRING NOT NULL,
    DECISION STRING NOT NULL,
    COMMENT STRING,
    DECIDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW ML_PROD.MLOPS.V_ACTIVE_MODELS AS
SELECT
    MODEL_NAME,
    MODEL_VERSION,
    OWNER,
    RISK_TIER,
    STAGE,
    ARTIFACT_URI,
    REGISTERED_AT
FROM ML_PROD.MLOPS.MODEL_REGISTRY
WHERE IS_ACTIVE = TRUE;
