-- Monitoring-ready views and alert candidates.

CREATE OR REPLACE TABLE ML_PROD.MLOPS.MODEL_PREDICTION_LOG (
    EVENT_TS TIMESTAMP_NTZ NOT NULL,
    MODEL_NAME STRING NOT NULL,
    MODEL_VERSION STRING NOT NULL,
    REQUEST_ID STRING,
    LATENCY_MS NUMBER(10,2),
    PREDICTION VARIANT,
    INPUT_HASH STRING,
    QUALITY_SIGNAL FLOAT,
    DRIFT_SCORE FLOAT
);

CREATE OR REPLACE VIEW ML_PROD.MLOPS.V_MODEL_HEALTH_DAILY AS
SELECT
    DATE_TRUNC('DAY', EVENT_TS) AS EVENT_DAY,
    MODEL_NAME,
    MODEL_VERSION,
    COUNT(*) AS REQUEST_COUNT,
    AVG(LATENCY_MS) AS AVG_LATENCY_MS,
    APPROX_PERCENTILE(LATENCY_MS, 0.95) AS P95_LATENCY_MS,
    AVG(QUALITY_SIGNAL) AS AVG_QUALITY_SIGNAL,
    AVG(DRIFT_SCORE) AS AVG_DRIFT_SCORE
FROM ML_PROD.MLOPS.MODEL_PREDICTION_LOG
GROUP BY 1, 2, 3;

-- Example alert query pattern (wire into Tasks/Alerts by environment):
-- SELECT *
-- FROM ML_PROD.MLOPS.V_MODEL_HEALTH_DAILY
-- WHERE EVENT_DAY = CURRENT_DATE - 1
--   AND (P95_LATENCY_MS > 1000 OR AVG_DRIFT_SCORE > 0.15 OR AVG_QUALITY_SIGNAL < 0.80);
