USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;

CREATE SCHEMA IF NOT EXISTS DEMO_DEV.FRAUD_INTELLIGENCE
    COMMENT = 'Fraud Intelligence Platform - Medallion Architecture (BRZ/SLV/GLD)';

GRANT USAGE ON SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE TO ROLE AGENT_DEMO_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE TO ROLE AGENT_DEMO_ROLE;
