USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;
USE SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE;

CREATE OR REPLACE TABLE BRZ_RAW_TRANSACTIONS (
    TRANSACTION_ID      VARCHAR(50)     NOT NULL,
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    ACCOUNT_ID          VARCHAR(50)     NOT NULL,
    TRANSACTION_DATE    TIMESTAMP_NTZ   NOT NULL,
    TRANSACTION_AMOUNT  NUMBER(18,2)    NOT NULL,
    TRANSACTION_TYPE    VARCHAR(50),
    MERCHANT_CATEGORY   VARCHAR(100),
    CHANNEL             VARCHAR(50),
    MERCHANT_NAME       VARCHAR(200),
    MERCHANT_COUNTRY    VARCHAR(5),
    DEVICE_ID           VARCHAR(100),
    IP_ADDRESS          VARCHAR(45),
    SOURCE_SYSTEM       VARCHAR(50)     DEFAULT 'CORE_BANKING',
    INGESTED_AT         TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw transaction events ingested from core banking system';

CREATE OR REPLACE TABLE BRZ_RAW_ALERTS (
    ALERT_ID            VARCHAR(50)     NOT NULL,
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    ALERT_DATE          TIMESTAMP_NTZ   NOT NULL,
    RULE_CODE           VARCHAR(20)     NOT NULL,
    RULE_DESCRIPTION    VARCHAR(500),
    ALERT_RISK_SCORE    NUMBER(5,2),
    ALERT_STATUS        VARCHAR(30),
    ANALYST_ID          VARCHAR(50),
    DISPOSITION         VARCHAR(50),
    SAR_FILED           BOOLEAN,
    TRANSACTION_ID      VARCHAR(50),
    SOURCE_SYSTEM       VARCHAR(50)     DEFAULT 'DETECTION_ENGINE',
    INGESTED_AT         TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw fraud/AML alert feed from detection engine';

CREATE OR REPLACE TABLE BRZ_RAW_CUSTOMERS (
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    FULL_NAME           VARCHAR(200),
    DATE_OF_BIRTH       DATE,
    SSN_LAST_FOUR       VARCHAR(4),
    EMAIL               VARCHAR(200),
    PHONE               VARCHAR(20),
    ADDRESS_LINE_1      VARCHAR(300),
    CITY                VARCHAR(100),
    STATE               VARCHAR(50),
    ZIP_CODE            VARCHAR(10),
    COUNTRY             VARCHAR(5),
    RISK_SEGMENT        VARCHAR(30),
    KYC_COMPLETE        BOOLEAN,
    IS_SYNTHETIC_FLAG   BOOLEAN,
    IS_MERGER_DUP_FLAG  BOOLEAN,
    CUSTOMER_SINCE      DATE,
    ACCOUNT_COUNT       NUMBER(5),
    SOURCE_SYSTEM       VARCHAR(50)     DEFAULT 'CRM',
    INGESTED_AT         TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw customer master from CRM/core banking';

CREATE OR REPLACE TABLE BRZ_RAW_VELOCITY_EVENTS (
    EVENT_ID            VARCHAR(50)     NOT NULL,
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    EVENT_TIMESTAMP     TIMESTAMP_NTZ   NOT NULL,
    TXN_COUNT_1H        NUMBER(10),
    TXN_COUNT_24H       NUMBER(10),
    TXN_AMOUNT_1H       NUMBER(18,2),
    TXN_AMOUNT_24H      NUMBER(18,2),
    DISTINCT_MERCHANTS_24H  NUMBER(10),
    RECENT_TXN_COUNT    NUMBER(10),
    RECENT_TXN_AMOUNT   NUMBER(18,2),
    FRAUD_RATE_7D       NUMBER(8,6),
    SOURCE_SYSTEM       VARCHAR(50)     DEFAULT 'STREAMING_PIPELINE',
    INGESTED_AT         TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw streaming velocity counter events from transaction pipeline';

CREATE OR REPLACE TABLE BRZ_RAW_INVESTIGATION_DOCS (
    DOC_ID              VARCHAR(50)     NOT NULL,
    DOC_TITLE           VARCHAR(500),
    DOC_CONTENT         VARCHAR(16777216),
    DOC_CATEGORY        VARCHAR(100),
    EFFECTIVE_DATE      DATE,
    SOURCE_SYSTEM       VARCHAR(50)     DEFAULT 'COMPLIANCE_PORTAL',
    INGESTED_AT         TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw investigation procedure documents from compliance portal';

CREATE OR REPLACE TABLE BRZ_RAW_RULE_DEFINITIONS (
    RULE_CODE           VARCHAR(20)     NOT NULL,
    RULE_NAME           VARCHAR(200),
    RULE_DESCRIPTION    VARCHAR(1000),
    RULE_CATEGORY       VARCHAR(100),
    RISK_WEIGHT         NUMBER(5,2),
    IS_ACTIVE           BOOLEAN         DEFAULT TRUE,
    CREATED_DATE        DATE,
    SOURCE_SYSTEM       VARCHAR(50)     DEFAULT 'DETECTION_ENGINE',
    INGESTED_AT         TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw detection rule definitions from detection engine';

CREATE OR REPLACE TABLE DEMO_DEV.FRAUD_INTELLIGENCE.BRZ_ANALYST_DECISIONS (
    DECISION_ID         VARCHAR(50)     NOT NULL,
    ALERT_ID            VARCHAR(50)     NOT NULL,
    TRANSACTION_ID      VARCHAR(50),
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    ANALYST_ID          VARCHAR(50),
    DECISION            VARCHAR(30),
    SAR_RECOMMENDED     BOOLEAN         DEFAULT FALSE,
    SAR_FILED           BOOLEAN         DEFAULT FALSE,
    SAR_FILED_DATE      DATE,
    SAR_FILED_TIMESTAMP TIMESTAMP_LTZ,
    ML_SCORE_AT_DECISION    NUMBER(5,4),
    AGENT_RECOMMENDATION    VARCHAR(50),
    AGENT_CONFIDENCE        VARCHAR(20),
    AGENT_REASONING_SUMMARY VARCHAR(2000),
    RULE_TRIGGERED          VARCHAR(20),
    RULE_ML_AGREEMENT       BOOLEAN,
    SAR_THRESHOLD_MET       BOOLEAN,
    CONFIDENCE_LEVEL        VARCHAR(20),
    DECISION_NOTES          VARCHAR(1000),
    AGENT_SCORED_AT         TIMESTAMP_LTZ,
    AGENT_REASONED_AT       TIMESTAMP_LTZ,
    DECISION_TIMESTAMP      TIMESTAMP_LTZ,
    SOURCE_SYSTEM           VARCHAR(50)     DEFAULT 'AGENT_ASSISTED_TRIAGE',
    INGESTED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Agent-assisted analyst fraud decisions — captures ML probabilistic score, LLM agent reasoning, rule agreement, and SAR filing decisions for model retraining lineage';




