USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;
USE SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE;

CREATE TAG IF NOT EXISTS PII_LEVEL
    ALLOWED_VALUES 'HIGH', 'MEDIUM', 'LOW'
    COMMENT = 'Classifies columns by PII sensitivity level';

CREATE TAG IF NOT EXISTS DATA_DOMAIN
    ALLOWED_VALUES 'FINANCIAL', 'IDENTITY', 'BEHAVIORAL', 'OPERATIONAL'
    COMMENT = 'Classifies columns by business data domain';

CREATE TAG IF NOT EXISTS DATA_LAYER
    ALLOWED_VALUES 'BRONZE', 'SILVER', 'GOLD'
    COMMENT = 'Identifies the medallion layer of the object';
