USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;
USE SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE;

CREATE MASKING POLICY IF NOT EXISTS MASK_PII_STRING AS (VAL STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('AGENT_DEMO_ROLE', 'SYSADMIN', 'ACCOUNTADMIN')
            THEN VAL
        ELSE '***MASKED***'
    END
COMMENT = 'Masks string PII columns for non-privileged roles';

CREATE MASKING POLICY IF NOT EXISTS MASK_PII_NUMBER AS (VAL NUMBER) RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('AGENT_DEMO_ROLE', 'SYSADMIN', 'ACCOUNTADMIN')
            THEN VAL
        ELSE -1
    END
COMMENT = 'Masks numeric PII columns for non-privileged roles';

CREATE MASKING POLICY IF NOT EXISTS MASK_PII_DATE AS (VAL DATE) RETURNS DATE ->
    CASE
        WHEN CURRENT_ROLE() IN ('AGENT_DEMO_ROLE', 'SYSADMIN', 'ACCOUNTADMIN')
            THEN VAL
        ELSE DATE_FROM_PARTS(1900, 1, 1)
    END
COMMENT = 'Masks date PII columns for non-privileged roles';
