USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;
USE SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE;

-- Tag Bronze tables with DATA_LAYER
ALTER TABLE BRZ_RAW_TRANSACTIONS SET TAG DATA_LAYER = 'BRONZE';
ALTER TABLE BRZ_RAW_ALERTS SET TAG DATA_LAYER = 'BRONZE';
ALTER TABLE BRZ_RAW_CUSTOMERS SET TAG DATA_LAYER = 'BRONZE';
ALTER TABLE BRZ_RAW_VELOCITY_EVENTS SET TAG DATA_LAYER = 'BRONZE';
ALTER TABLE BRZ_RAW_INVESTIGATION_DOCS SET TAG DATA_LAYER = 'BRONZE';
ALTER TABLE BRZ_RAW_RULE_DEFINITIONS SET TAG DATA_LAYER = 'BRONZE';

-- Tag PII columns - HIGH sensitivity (direct identifiers)
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN FULL_NAME SET TAG PII_LEVEL = 'HIGH';
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN SSN_LAST_FOUR SET TAG PII_LEVEL = 'HIGH';
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN EMAIL SET TAG PII_LEVEL = 'HIGH';
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN PHONE SET TAG PII_LEVEL = 'HIGH';
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN DATE_OF_BIRTH SET TAG PII_LEVEL = 'HIGH';

-- Tag PII columns - MEDIUM sensitivity (quasi-identifiers)
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN ADDRESS_LINE_1 SET TAG PII_LEVEL = 'MEDIUM';
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN ZIP_CODE SET TAG PII_LEVEL = 'MEDIUM';
ALTER TABLE BRZ_RAW_TRANSACTIONS MODIFY COLUMN IP_ADDRESS SET TAG PII_LEVEL = 'MEDIUM';
ALTER TABLE BRZ_RAW_TRANSACTIONS MODIFY COLUMN DEVICE_ID SET TAG PII_LEVEL = 'MEDIUM';

-- Tag PII columns - LOW sensitivity (indirect identifiers)
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN CUSTOMER_ID SET TAG PII_LEVEL = 'LOW';
ALTER TABLE BRZ_RAW_TRANSACTIONS MODIFY COLUMN CUSTOMER_ID SET TAG PII_LEVEL = 'LOW';
ALTER TABLE BRZ_RAW_ALERTS MODIFY COLUMN CUSTOMER_ID SET TAG PII_LEVEL = 'LOW';

-- Tag DATA_DOMAIN
ALTER TABLE BRZ_RAW_TRANSACTIONS MODIFY COLUMN TRANSACTION_AMOUNT SET TAG DATA_DOMAIN = 'FINANCIAL';
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN FULL_NAME SET TAG DATA_DOMAIN = 'IDENTITY';
ALTER TABLE BRZ_RAW_VELOCITY_EVENTS MODIFY COLUMN TXN_COUNT_1H SET TAG DATA_DOMAIN = 'BEHAVIORAL';

-- Apply masking policies to HIGH PII columns
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN FULL_NAME SET MASKING POLICY MASK_PII_STRING;
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN SSN_LAST_FOUR SET MASKING POLICY MASK_PII_STRING;
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN EMAIL SET MASKING POLICY MASK_PII_STRING;
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN PHONE SET MASKING POLICY MASK_PII_STRING;
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN DATE_OF_BIRTH SET MASKING POLICY MASK_PII_DATE;

-- Apply masking to MEDIUM PII columns
ALTER TABLE BRZ_RAW_CUSTOMERS MODIFY COLUMN ADDRESS_LINE_1 SET MASKING POLICY MASK_PII_STRING;
ALTER TABLE BRZ_RAW_TRANSACTIONS MODIFY COLUMN IP_ADDRESS SET MASKING POLICY MASK_PII_STRING;
ALTER TABLE BRZ_RAW_TRANSACTIONS MODIFY COLUMN DEVICE_ID SET MASKING POLICY MASK_PII_STRING;
