USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;
USE SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE;

CREATE OR REPLACE TASK TASK_ML_TRAINING_ROOT
    WAREHOUSE = 'AGENT_DEMO_WH'
    SCHEDULE = 'USING CRON 0 2 * * 0 UTC'
    COMMENT = 'Weekly ML model training pipeline - runs Sunday 2AM UTC'
AS
    SELECT 1;

CREATE OR REPLACE TASK TASK_ML_FEATURE_PREP
    WAREHOUSE = 'AGENT_DEMO_WH'
    AFTER DEMO_DEV.FRAUD_INTELLIGENCE.TASK_ML_TRAINING_ROOT
    COMMENT = 'Prepare GLD_ML_TRAINING_SET from latest Silver features'
AS
    EXECUTE DBT PROJECT FRAUD_INTELLIGENCE_DBT
        ARGS = 'run --select gld_ml_training_set --target dev';

CREATE OR REPLACE TASK TASK_ML_TRAIN_MODEL
    WAREHOUSE = 'AGENT_DEMO_WH'
    AFTER DEMO_DEV.FRAUD_INTELLIGENCE.TASK_ML_FEATURE_PREP
    COMMENT = 'Execute training notebook: trains XGBClassifier on GLD_ML_TRAINING_SET with agent-labelled fraud data, registers model to ML Registry, logs performance to SLV_MODEL_PERFORMANCE_LOG'
AS
    EXECUTE NOTEBOOK PROJECT DEMO_DEV.FRAUD_INTELLIGENCE.FRAUD_TRAINING_NOTEBOOK_PROJECT
        MAIN_FILE = 'fraud_intelligence/notebooks/train_fraud_detection_model.ipynb'
        COMPUTE_POOL = 'AGENT_DEMO'
        QUERY_WAREHOUSE = 'AGENT_DEMO_WH'
        RUNTIME = 'V2.2-CPU-PY3.11';

DROP TASK IF EXISTS DEMO_DEV.FRAUD_INTELLIGENCE.TASK_ML_LOG_PERFORMANCE;
