USE ROLE AGENT_DEMO_ROLE;
USE WAREHOUSE AGENT_DEMO_WH;
USE SCHEMA DEMO_DEV.FRAUD_INTELLIGENCE;

CREATE OR REPLACE TASK TASK_ML_INFERENCE_ROOT
    WAREHOUSE = 'AGENT_DEMO_WH'
    AFTER DEMO_DEV.FRAUD_INTELLIGENCE.TASK_SLV_TO_GLD_ENRICHMENT
    COMMENT = 'ML inference pipeline - runs after ETL Gold layer completes'
AS
    SELECT 1;

CREATE OR REPLACE TASK TASK_ML_SCORE_ALERTS
    WAREHOUSE = 'AGENT_DEMO_WH'
    AFTER DEMO_DEV.FRAUD_INTELLIGENCE.TASK_ML_INFERENCE_ROOT
    COMMENT = 'Score new enriched alerts using fraud detection model'
AS
    CALL DEMO_DEV.FRAUD_INTELLIGENCE.SCORE_TRANSACTION('BATCH');

CREATE OR REPLACE TASK TASK_ML_UPDATE_SCORES
    WAREHOUSE = 'AGENT_DEMO_WH'
    AFTER DEMO_DEV.FRAUD_INTELLIGENCE.TASK_ML_SCORE_ALERTS
    COMMENT = 'Update Gold scoring view with latest ML predictions'
AS
    EXECUTE DBT PROJECT FRAUD_INTELLIGENCE_DBT
        ARGS = 'run --select gld_alert_enrichment_with_scoring --target dev';
