SELECT
    SUMMARY_RECORD_ID,
    FEED_RUN_ID,
    GOLD_LAST_REFRESHED_AT,
    CATEGORY,
    TOTAL_ACTIVE_SKUS_IN_CATEGORY,
    COUNT_OVERPRICED_SKUS,
    COUNT_UNDERPRICED_SKUS,
    COUNT_AT_PRICE_PARITY_SKUS,
    COUNT_OUT_OF_STOCK_SKUS,
    COUNT_LOW_STOCK_SKUS,
    AVERAGE_MARGIN_PERCENTAGE,
    TOTAL_INVENTORY_RETAIL_VALUE_USD,
    COUNT_SKUS_NEEDING_PRICE_ACTION,
    COUNT_SKUS_NEEDING_REPLENISHMENT
FROM {{ source('retail_category_analytics', 'GOLD_CATEGORY_PERFORMANCE_SUMMARY') }}
