SELECT
    SKU_ID,
    PRODUCT_NAME,
    BRAND,
    CATEGORY,
    TOTAL_RETURNS,
    TOTAL_UNITS_SOLD,
    RETURN_RATE_PCT,
    TOTAL_REFUND_USD,
    TOTAL_MARGIN_LOST_USD,
    AVG_DAYS_TO_RETURN,
    TOP_RETURN_REASON,
    TOP_RETURN_CONDITION,
    ONLINE_RETURN_PCT,
    RECOMMENDED_ACTION,
    RATIONALIZATION_FLAG
FROM {{ source('retail_category_analytics', 'GOLD_RETURNS_MARGIN_ANALYSIS') }}
