-- ============================================================
-- DEFINE Access Control Definitions (DCM Managed)
-- Role and Grants for RETAIL_CATEGORY_ANALYTICS_AGENT
-- ============================================================

DEFINE ROLE RETAIL_CATEGORY_ANALYTICS_ROLE
    COMMENT = 'Dedicated role for the Retail Category Analytics Agent. Scoped to DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT schema only.';

-- ============================================================
-- Account-Level Privileges
-- ============================================================

GRANT EXECUTE TASK ON ACCOUNT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT EXECUTE MANAGED TASK ON ACCOUNT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

-- ============================================================
-- Database Privileges
-- ============================================================

GRANT USAGE ON DATABASE DEMO_DEV
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT MONITOR ON DATABASE DEMO_DEV
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT USAGE ON DATABASE ADMIN_DB
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

-- ============================================================
-- Schema Privileges
-- ============================================================

GRANT USAGE ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE TABLE ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE VIEW ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE STAGE ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE TASK ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE PROCEDURE ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE FUNCTION ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE STREAMLIT ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE DYNAMIC TABLE ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE FILE FORMAT ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE SECRET ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE TAG ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE AGENT ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE SEMANTIC VIEW ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT CREATE GIT REPOSITORY ON SCHEMA DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT USAGE ON SCHEMA DEMO_DEV.PUBLIC
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT USAGE ON SCHEMA ADMIN_DB.SECRETS
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

-- ============================================================
-- Warehouse Privileges
-- ============================================================

GRANT USAGE ON WAREHOUSE RETAIL_CATEGORY_ANALYTICS_WH
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

-- ============================================================
-- Database Role Privileges
-- ============================================================

GRANT USAGE ON DATABASE ROLE SNOWFLAKE.CORTEX_USER
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT USAGE ON DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT USAGE ON DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

-- ============================================================
-- Integration Privileges
-- ============================================================

GRANT USAGE ON INTEGRATION SERPAPI_ACCESS_INTEGRATION
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT USAGE ON INTEGRATION SF_GITHUB_INTEGRATION
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

-- ============================================================
-- Secret Privileges
-- ============================================================

GRANT USAGE ON SECRET ADMIN_DB.SECRETS.SF_GITHUB_PAT
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

GRANT USAGE ON SECRET ADMIN_DB.SECRETS.SF_GITHUB_PAT_JAYA
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

-- ============================================================
-- Stage Privileges
-- ============================================================

GRANT READ ON STAGE DEMO_DEV.PUBLIC.SHARED_ASSETS
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;

-- ============================================================
-- Role Hierarchy
-- ============================================================

GRANT USAGE ON ROLE WORKSPACES_STEWARD
    TO ROLE RETAIL_CATEGORY_ANALYTICS_ROLE;
