-- Access control: Roles and Grants
-- Add your role and grant definitions here.

DEFINE ROLE SANDBOX.TPCH.DATA_READER{{env_suffix}};

GRANT USAGE ON WAREHOUSE SANDBOX.TPCH.ANALYTICS_WH{{env_suffix}}
    TO ROLE SANDBOX.TPCH.DATA_READER{{env_suffix}};

GRANT SELECT ON TABLE SANDBOX.TPCH.CUSTOMERS
    TO ROLE SANDBOX.TPCH.DATA_READER{{env_suffix}};

GRANT SELECT ON TABLE SANDBOX.TPCH.ORDERS
    TO ROLE SANDBOX.TPCH.DATA_READER{{env_suffix}};

GRANT SELECT ON VIEW SANDBOX.TPCH.CUSTOMER_ORDER_SUMMARY
    TO ROLE SANDBOX.TPCH.DATA_READER{{env_suffix}};
