-- Access control: Roles and Grants
-- Add your role and grant definitions here.

DEFINE ROLE DATA_READER{{env_suffix}};

GRANT USAGE ON WAREHOUSE ANALYTICS_WH{{env_suffix}}
    TO ROLE DATA_READER{{env_suffix}};

GRANT SELECT ON TABLE SANDBOX.TPCH.CUSTOMERS
    TO ROLE DATA_READER{{env_suffix}};

GRANT SELECT ON TABLE SANDBOX.TPCH.ORDERS
    TO ROLE DATA_READER{{env_suffix}};

GRANT SELECT ON VIEW SANDBOX.TPCH.CUSTOMER_ORDER_SUMMARY
    TO ROLE DATA_READER{{env_suffix}};
