-- ============================================================
-- DEFINE Dynamic Table Definitions (DCM Managed)
-- Schema: DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
-- Auto-refreshing materialized views (Snowflake-managed pipeline).
-- ============================================================

DEFINE DYNAMIC TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_CATEGORY_PERFORMANCE_SUMMARY (
    SUMMARY_RECORD_ID,
    FEED_RUN_ID,
    GOLD_LAST_REFRESHED_AT,
    CATEGORY,
    TOTAL_ACTIVE_SKUS_IN_CATEGORY,
    COUNT_OVERPRICED_SKUS,
    COUNT_UNDERPRICED_SKUS,
    COUNT_AT_PRICE_PARITY_SKUS,
    COUNT_OUT_OF_STOCK_SKUS,
    COUNT_LOW_STOCK_SKUS,
    AVERAGE_MARGIN_PERCENTAGE,
    TOTAL_INVENTORY_RETAIL_VALUE_USD,
    COUNT_SKUS_NEEDING_PRICE_ACTION,
    COUNT_SKUS_NEEDING_REPLENISHMENT
)
    TARGET_LAG = '30 minutes'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = RETAIL_CATEGORY_ANALYTICS_WH
    COMMENT = 'Dynamic table. Category-level KPI summary. Auto-refreshes when GOLD_SKU_PRICING_INTELLIGENCE changes.'
AS
    SELECT
        MD5(FEED_RUN_ID || '|' || CATEGORY) AS SUMMARY_RECORD_ID,
        FEED_RUN_ID,
        MAX(GOLD_LAST_REFRESHED_AT) AS GOLD_LAST_REFRESHED_AT,
        CATEGORY,
        COUNT(*) AS TOTAL_ACTIVE_SKUS_IN_CATEGORY,
        COUNT(CASE WHEN OVERALL_COMPETITIVE_POSITIONING_STATUS = 'OVERPRICED' THEN 1 END) AS COUNT_OVERPRICED_SKUS,
        COUNT(CASE WHEN OVERALL_COMPETITIVE_POSITIONING_STATUS = 'UNDERPRICED' THEN 1 END) AS COUNT_UNDERPRICED_SKUS,
        COUNT(CASE WHEN OVERALL_COMPETITIVE_POSITIONING_STATUS = 'PRICE_PARITY' THEN 1 END) AS COUNT_AT_PRICE_PARITY_SKUS,
        COUNT(CASE WHEN STOCK_AVAILABILITY_STATUS = 'OUT_OF_STOCK' THEN 1 END) AS COUNT_OUT_OF_STOCK_SKUS,
        COUNT(CASE WHEN STOCK_AVAILABILITY_STATUS = 'LOW_STOCK' THEN 1 END) AS COUNT_LOW_STOCK_SKUS,
        ROUND(AVG(OUR_MARGIN_PERCENTAGE), 2) AS AVERAGE_MARGIN_PERCENTAGE,
        ROUND(SUM(OUR_CURRENT_PRICE * CURRENT_STOCK_LEVEL), 2) AS TOTAL_INVENTORY_RETAIL_VALUE_USD,
        COUNT(CASE WHEN REQUIRES_IMMEDIATE_PRICE_REVIEW = TRUE THEN 1 END) AS COUNT_SKUS_NEEDING_PRICE_ACTION,
        COUNT(CASE WHEN REQUIRES_REPLENISHMENT_ACTION = TRUE THEN 1 END) AS COUNT_SKUS_NEEDING_REPLENISHMENT
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_SKU_PRICING_INTELLIGENCE
    GROUP BY FEED_RUN_ID, CATEGORY;
