-- ============================================================
-- DEFINE TABLE Definitions (DCM Managed)
-- Schema: DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
-- Layers: Bronze / Silver / Gold
-- ============================================================

-- ============================================================
-- BRONZE LAYER — Raw ingestion tables
-- ============================================================

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_COMPETITOR_PRICE_RAW (
    SNAPSHOT_RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    FEED_RUN_ID VARCHAR(16777216) NOT NULL,
    INGESTION_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SKU_ID VARCHAR(16777216),
    PRODUCT_SEARCH_QUERY VARCHAR(16777216),
    COMPETITOR_NAME VARCHAR(16777216),
    COMPETITOR_PRICE_RAW VARCHAR(16777216),
    COMPETITOR_IN_STOCK_STATUS VARCHAR(16777216),
    COMPETITOR_PRODUCT_URL VARCHAR(16777216),
    SERPAPI_FULL_RESPONSE_JSON VARIANT,
    SCRAPED_AT TIMESTAMP_LTZ(9)
)
    COMMENT = 'Bronze layer raw SerpAPI competitor price data. Each row is a single competitor product match returned by the Google Shopping API for a given SKU search term. Full JSON response preserved for reprocessing.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_LOYALTY_MEMBERS_RAW (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MEMBER_ID VARCHAR(16777216) NOT NULL,
    FIRST_NAME VARCHAR(16777216) NOT NULL,
    LAST_NAME VARCHAR(16777216) NOT NULL,
    EMAIL VARCHAR(16777216),
    ENROLLMENT_DATE DATE NOT NULL,
    TIER VARCHAR(16777216) NOT NULL COMMENT 'PLATINUM, GOLD, SILVER, STANDARD',
    PREFERRED_CATEGORY VARCHAR(16777216),
    PREFERRED_CHANNEL VARCHAR(16777216) DEFAULT 'OMNI' COMMENT 'ONLINE, IN_STORE, OMNI',
    LOYALTY_POINTS_BALANCE NUMBER(38,0) DEFAULT 0,
    STATUS VARCHAR(16777216) DEFAULT 'ACTIVE' COMMENT 'ACTIVE, INACTIVE, CHURNED',
    SOURCE_SYSTEM VARCHAR(16777216) DEFAULT 'LOYALTY_CRM'
)
    COMMENT = 'Bronze layer. Raw loyalty program membership records as received from CRM system. Each row is a single customer enrolled in the loyalty program.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_LOYALTY_TRANSACTIONS_RAW (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    TRANSACTION_ID VARCHAR(16777216) NOT NULL,
    MEMBER_ID VARCHAR(16777216) NOT NULL,
    SKU_ID VARCHAR(16777216) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    UNITS_PURCHASED NUMBER(38,0) DEFAULT 1,
    TRANSACTION_AMOUNT_USD FLOAT NOT NULL,
    POINTS_EARNED NUMBER(38,0) DEFAULT 0,
    CHANNEL VARCHAR(16777216) DEFAULT 'ONLINE' COMMENT 'ONLINE, IN_STORE',
    SOURCE_SYSTEM VARCHAR(16777216) DEFAULT 'POS_LOYALTY'
)
    COMMENT = 'Bronze layer. Raw purchase transactions by loyalty program members. Each row is a single purchase event linked to a member and SKU.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_PROMOTIONS_RAW (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PROMOTION_ID VARCHAR(16777216) NOT NULL,
    PROMOTION_NAME VARCHAR(16777216) NOT NULL,
    PROMOTION_TYPE VARCHAR(16777216) NOT NULL COMMENT 'MARKDOWN, BUNDLE, BOGO, CLEARANCE, SEASONAL',
    DISCOUNT_TYPE VARCHAR(16777216) NOT NULL COMMENT 'PERCENTAGE, FIXED_AMOUNT, BUY_X_GET_Y',
    DISCOUNT_VALUE FLOAT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    TARGET_CATEGORY VARCHAR(16777216),
    TARGET_BRAND VARCHAR(16777216),
    CHANNEL VARCHAR(16777216) DEFAULT 'OMNI' COMMENT 'IN_STORE, ONLINE, OMNI',
    PLANNED_UNIT_LIFT_PCT FLOAT,
    PLANNED_REVENUE_TARGET_USD FLOAT,
    STATUS VARCHAR(16777216) DEFAULT 'PLANNED' COMMENT 'PLANNED, ACTIVE, COMPLETED, CANCELLED',
    BUDGET_USD FLOAT,
    SOURCE_SYSTEM VARCHAR(16777216) DEFAULT 'MERCHANDISING_PLANNING'
)
    COMMENT = 'Bronze layer. Raw promotion definitions as received from merchandising/planning system. Each row represents a single promotional campaign.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_PROMOTION_SKU_ASSIGNMENTS_RAW (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    ASSIGNMENT_ID VARCHAR(16777216) NOT NULL,
    PROMOTION_ID VARCHAR(16777216) NOT NULL,
    SKU_ID VARCHAR(16777216) NOT NULL,
    ORIGINAL_PRICE FLOAT,
    PROMO_PRICE FLOAT,
    SOURCE_SYSTEM VARCHAR(16777216) DEFAULT 'MERCHANDISING_PLANNING'
)
    COMMENT = 'Bronze layer. Maps SKUs to promotional campaigns. Each row is a single SKU participation in a promotion with before/after pricing.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_RETURNS_RAW (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    RETURN_ID VARCHAR(16777216) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    RETURN_DATE DATE NOT NULL,
    SKU_ID VARCHAR(16777216) NOT NULL,
    UNITS_RETURNED NUMBER(38,0) DEFAULT 1,
    RETURN_REASON VARCHAR(16777216) NOT NULL COMMENT 'DEFECTIVE, WRONG_ITEM, NOT_AS_DESCRIBED, CHANGED_MIND, BETTER_PRICE_FOUND, SIZE_FIT_ISSUE',
    RETURN_CONDITION VARCHAR(16777216) COMMENT 'NEW, OPEN_BOX, DAMAGED, DEFECTIVE',
    REFUND_AMOUNT_USD FLOAT NOT NULL,
    CHANNEL VARCHAR(16777216) DEFAULT 'ONLINE' COMMENT 'ONLINE, IN_STORE',
    RESOLUTION VARCHAR(16777216) DEFAULT 'FULL_REFUND' COMMENT 'FULL_REFUND, EXCHANGE, STORE_CREDIT, REJECTED',
    SOURCE_SYSTEM VARCHAR(16777216) DEFAULT 'RMA_SYSTEM'
)
    COMMENT = 'Bronze layer. Raw product return events from the RMA system. Each row is a single return transaction linked to a SKU and original order.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_SERPAPI_FEED_RUN_LOG (
    FEED_RUN_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    RUN_TRIGGERED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    RUN_COMPLETED_AT TIMESTAMP_LTZ(9),
    RUN_TRIGGERED_BY VARCHAR(16777216),
    RUN_STATUS VARCHAR(16777216),
    TOTAL_SKUS_ATTEMPTED NUMBER(38,0) DEFAULT 0,
    TOTAL_SKUS_SUCCESSFULLY_FETCHED NUMBER(38,0) DEFAULT 0,
    TOTAL_PRICE_ROWS_WRITTEN NUMBER(38,0) DEFAULT 0,
    SKUS_WITH_FETCH_ERRORS NUMBER(38,0) DEFAULT 0,
    ERROR_SUMMARY VARCHAR(16777216),
    SERPAPI_API_CREDITS_CONSUMED FLOAT,
    RUN_DURATION_SECONDS FLOAT
)
    COMMENT = 'Operational log for every SerpAPI competitor price feed run. Tracks execution status, SKU fetch counts, error rates, API credit consumption, and duration for observability and cost governance.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_SKU_MASTER_RAW (
    INGESTION_RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    INGESTION_BATCH_ID VARCHAR(16777216),
    INGESTION_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME VARCHAR(16777216),
    SKU_ID VARCHAR(16777216),
    PRODUCT_NAME VARCHAR(16777216),
    CATEGORY VARCHAR(16777216),
    SUBCATEGORY VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    CURRENT_PRICE VARCHAR(16777216),
    COST VARCHAR(16777216),
    MARGIN_PCT VARCHAR(16777216),
    STOCK_LEVEL VARCHAR(16777216),
    IS_ACTIVE VARCHAR(16777216),
    COMPETITOR_REFERENCE_SEARCH_TERM VARCHAR(16777216),
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_ROW_HAS_PARSE_ERROR BOOLEAN DEFAULT FALSE,
    RAW_ROW_ERROR_DETAIL VARCHAR(16777216)
)
    COMMENT = 'Bronze layer raw SKU master data. Ingested as-is from CSV uploads with all business fields as STRING. No transformations applied. Parse errors are flagged inline for downstream quality checks.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.BRONZE_WEEKLY_SALES_RAW (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    WEEK_START_DATE DATE NOT NULL,
    WEEK_NUMBER NUMBER(38,0) NOT NULL,
    SKU_ID VARCHAR(16777216) NOT NULL,
    BRAND_RAW VARCHAR(16777216),
    CATEGORY_RAW VARCHAR(16777216),
    UNITS_SOLD NUMBER(38,0),
    REVENUE_USD FLOAT,
    SOURCE_SYSTEM VARCHAR(16777216) DEFAULT 'POS_SIMULATOR',
    FISCAL_QUARTER VARCHAR(16777216)
)
    COMMENT = 'Bronze layer. Raw weekly point-of-sale transaction data by SKU. Simulates POS feed ingestion for sell-through trend analysis.';

-- ============================================================
-- SILVER LAYER — Cleansed and enriched tables
-- ============================================================

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.SILVER_COMPETITOR_PRICE_ENRICHED (
    SILVER_RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    BRONZE_SNAPSHOT_RECORD_ID VARCHAR(16777216),
    FEED_RUN_ID VARCHAR(16777216) NOT NULL,
    SILVER_PROCESSED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SKU_ID VARCHAR(16777216) NOT NULL,
    PRODUCT_NAME VARCHAR(16777216),
    CATEGORY VARCHAR(16777216),
    COMPETITOR_NAME VARCHAR(16777216) NOT NULL,
    COMPETITOR_PRICE FLOAT,
    OUR_CURRENT_PRICE FLOAT,
    SCRAPED_AT TIMESTAMP_LTZ(9),
    PRICE_GAP_ABSOLUTE_USD FLOAT COMMENT 'Our price minus competitor price; positive means we are more expensive',
    PRICE_GAP_PERCENTAGE FLOAT COMMENT 'price_gap_absolute_usd divided by competitor_price times 100',
    COMPETITIVE_POSITIONING_STATUS VARCHAR(16777216) COMMENT 'OVERPRICED if gap pct > 5, UNDERPRICED if < -5, PRICE_PARITY otherwise',
    COMPETITOR_HAS_PRODUCT_IN_STOCK BOOLEAN,
    IS_SIGNIFICANT_PRICE_OPPORTUNITY BOOLEAN DEFAULT FALSE COMMENT 'TRUE when we are more than 10 percent overpriced vs this competitor',
    IS_STOCKOUT_OPPORTUNITY BOOLEAN DEFAULT FALSE COMMENT 'TRUE when competitor is out of stock and we have inventory'
)
    COMMENT = 'Silver layer enriched competitor price data. Combines raw SerpAPI results with our SKU pricing to compute absolute and percentage price gaps, competitive positioning status, and actionable opportunity flags.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.SILVER_DATA_QUALITY_CHECK_LOG (
    CHECK_RUN_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    CHECK_EXECUTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CHECK_NAME VARCHAR(16777216) NOT NULL,
    TARGET_TABLE_NAME VARCHAR(16777216) NOT NULL,
    TARGET_LAYER VARCHAR(16777216),
    TOTAL_ROWS_EVALUATED NUMBER(38,0),
    ROWS_THAT_PASSED NUMBER(38,0),
    ROWS_THAT_FAILED NUMBER(38,0),
    FAILURE_RATE_PERCENTAGE FLOAT,
    OVERALL_CHECK_PASSED BOOLEAN,
    SAMPLE_OF_FAILING_ROWS VARIANT,
    CHECK_TRIGGERED_BY VARCHAR(16777216)
)
    COMMENT = 'Logs every data quality check execution across Bronze and Silver layers. Captures row-level pass/fail counts, failure rates, sample failing rows as VARIANT for debugging, and trigger source for audit trail.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.SILVER_LOYALTY_MEMBERS_ENRICHED (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    PROCESSED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MEMBER_ID VARCHAR(16777216) NOT NULL,
    FIRST_NAME VARCHAR(16777216),
    LAST_NAME VARCHAR(16777216),
    EMAIL VARCHAR(16777216),
    ENROLLMENT_DATE DATE,
    TIER VARCHAR(16777216),
    PREFERRED_CATEGORY VARCHAR(16777216),
    PREFERRED_CHANNEL VARCHAR(16777216),
    LOYALTY_POINTS_BALANCE NUMBER(38,0),
    STATUS VARCHAR(16777216),
    TOTAL_TRANSACTIONS NUMBER(38,0),
    TOTAL_SPEND_USD FLOAT,
    AVG_ORDER_VALUE FLOAT,
    TOTAL_UNITS_PURCHASED NUMBER(38,0),
    TOTAL_POINTS_EARNED NUMBER(38,0),
    FIRST_PURCHASE_DATE DATE,
    LAST_PURCHASE_DATE DATE,
    DAYS_SINCE_LAST_PURCHASE NUMBER(38,0),
    TOP_CATEGORY VARCHAR(16777216),
    TOP_BRAND VARCHAR(16777216),
    TENURE_DAYS NUMBER(38,0)
)
    COMMENT = 'Silver layer. Enriched loyalty member profiles with aggregated purchase metrics. One row per member with computed transaction summaries and category/brand affinities.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.SILVER_PROMOTIONS_ENRICHED (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    PROCESSED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PROMOTION_ID VARCHAR(16777216) NOT NULL,
    PROMOTION_NAME VARCHAR(16777216) NOT NULL,
    PROMOTION_TYPE VARCHAR(16777216) NOT NULL,
    DISCOUNT_TYPE VARCHAR(16777216) NOT NULL,
    DISCOUNT_VALUE FLOAT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    TARGET_CATEGORY VARCHAR(16777216),
    TARGET_BRAND VARCHAR(16777216),
    CHANNEL VARCHAR(16777216),
    PLANNED_UNIT_LIFT_PCT FLOAT,
    PLANNED_REVENUE_TARGET_USD FLOAT,
    STATUS VARCHAR(16777216),
    BUDGET_USD FLOAT,
    PROMO_DURATION_DAYS NUMBER(38,0),
    SKU_ID VARCHAR(16777216),
    PRODUCT_NAME VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    CATEGORY VARCHAR(16777216),
    ORIGINAL_PRICE FLOAT,
    PROMO_PRICE FLOAT,
    DISCOUNT_AMOUNT_USD FLOAT,
    DISCOUNT_PERCENTAGE FLOAT,
    IS_CURRENTLY_ACTIVE BOOLEAN DEFAULT FALSE
)
    CHANGE_TRACKING = TRUE
    COMMENT = 'Silver layer. Enriched promotion data joining Bronze promotions + SKU assignments with SKU master details. One row per promotion-SKU combination.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.SILVER_RETURNS_ENRICHED (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    PROCESSED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    RETURN_ID VARCHAR(16777216) NOT NULL,
    ORDER_DATE DATE,
    RETURN_DATE DATE,
    SKU_ID VARCHAR(16777216) NOT NULL,
    PRODUCT_NAME VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    CATEGORY VARCHAR(16777216),
    UNITS_RETURNED NUMBER(38,0),
    RETURN_REASON VARCHAR(16777216),
    RETURN_CONDITION VARCHAR(16777216),
    REFUND_AMOUNT_USD FLOAT,
    CHANNEL VARCHAR(16777216),
    RESOLUTION VARCHAR(16777216),
    OUR_MARGIN_PERCENTAGE FLOAT,
    MARGIN_LOST_USD FLOAT,
    DAYS_TO_RETURN NUMBER(38,0)
)
    CHANGE_TRACKING = TRUE
    COMMENT = 'Silver layer. Enriched return events joined with SKU master for product details and computed margin impact. One row per return transaction.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.SILVER_SKU_MASTER_CLEANSED (
    SILVER_RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    BRONZE_INGESTION_BATCH_ID VARCHAR(16777216),
    SILVER_PROCESSED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    IS_CURRENT_RECORD BOOLEAN DEFAULT TRUE,
    SKU_ID VARCHAR(16777216) NOT NULL,
    PRODUCT_NAME VARCHAR(16777216) NOT NULL,
    CATEGORY VARCHAR(16777216) NOT NULL,
    SUBCATEGORY VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    CURRENT_PRICE FLOAT,
    COST FLOAT,
    MARGIN_PCT FLOAT,
    MARGIN_AMOUNT_USD FLOAT COMMENT 'Derived: current_price minus cost',
    STOCK_LEVEL NUMBER(38,0) DEFAULT 0,
    STOCK_AVAILABILITY_STATUS VARCHAR(16777216) COMMENT 'Derived: IN_STOCK when stock_level > 50, LOW_STOCK when 1-50, OUT_OF_STOCK when 0',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    COMPETITOR_REFERENCE_SEARCH_TERM VARCHAR(16777216),
    RECORD_SOURCE_CREATED_AT TIMESTAMP_LTZ(9),
    RECORD_SOURCE_UPDATED_AT TIMESTAMP_LTZ(9),
    DATA_QUALITY_CHECK_PASSED BOOLEAN DEFAULT TRUE,
    DATA_QUALITY_FAILURE_REASON VARCHAR(16777216)
)
    CHANGE_TRACKING = TRUE
    COMMENT = 'Silver layer cleansed SKU master data. Type-cast from Bronze with validation, derived margin and stock status fields, and SCD Type 2 support for historical tracking.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.SILVER_WEEKLY_SALES_CLEANSED (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    PROCESSED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    WEEK_START_DATE DATE NOT NULL,
    WEEK_NUMBER NUMBER(38,0) NOT NULL,
    SKU_ID VARCHAR(16777216) NOT NULL,
    BRAND VARCHAR(16777216) NOT NULL,
    CATEGORY VARCHAR(16777216) NOT NULL,
    UNITS_SOLD NUMBER(38,0) NOT NULL,
    REVENUE_USD FLOAT NOT NULL,
    FISCAL_QUARTER VARCHAR(16777216),
    IS_VALID BOOLEAN DEFAULT TRUE
)
    CHANGE_TRACKING = TRUE
    COMMENT = 'Silver layer. Cleansed and standardized weekly sales data. NULL brands/categories removed, units validated > 0.';

-- ============================================================
-- GOLD LAYER — Analytics-ready tables
-- ============================================================

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_ACTION_EXECUTION_AUDIT (
    AUDIT_RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    ACTION_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SNOWFLAKE_USER_WHO_EXECUTED_ACTION VARCHAR(16777216) NOT NULL,
    SNOWFLAKE_QUERY_ID VARCHAR(16777216),
    ACTION_TYPE VARCHAR(16777216) NOT NULL COMMENT 'REPRICE, REPLENISH, MONITOR, ESCALATE',
    SKU_ID VARCHAR(16777216) NOT NULL,
    PRODUCT_NAME VARCHAR(16777216),
    ACTION_INPUT_PARAMETERS VARIANT,
    VALUE_BEFORE_ACTION VARCHAR(16777216),
    VALUE_AFTER_ACTION VARCHAR(16777216),
    ACTION_REASON_OR_JUSTIFICATION VARCHAR(16777216),
    EXECUTION_STATUS VARCHAR(16777216) DEFAULT 'SUCCESS',
    SYSTEM_RESPONSE_MESSAGE VARCHAR(16777216),
    WAS_THIS_ACTION_AI_SUGGESTED BOOLEAN DEFAULT FALSE,
    IS_ROLLBACK_POSSIBLE BOOLEAN DEFAULT FALSE
)
    COMMENT = 'Gold layer. Immutable audit trail. Records every SKU-level action taken from the Streamlit dashboard including repricing, replenishment, campaign drafts, and marketing queues with full before/after state.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_AGENT_CONVERSATION_LOG (
    CONVERSATION_RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    CHAT_SESSION_IDENTIFIER VARCHAR(16777216),
    SNOWFLAKE_USERNAME VARCHAR(16777216),
    INTERACTION_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    USER_QUESTION VARCHAR(16777216),
    AGENT_RESPONSE VARCHAR(16777216),
    SQL_QUERY_GENERATED VARCHAR(16777216),
    RESPONSE_LATENCY_MS NUMBER(38,0),
    CORTEX_MODEL_USED VARCHAR(16777216)
)
    COMMENT = 'Gold layer. One row per user-agent interaction. Captures question, response, SQL generated, and latency for audit and analytics.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_LOYALTY_CUSTOMER_INSIGHTS (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    GOLD_REFRESHED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MEMBER_ID VARCHAR(16777216) NOT NULL,
    FULL_NAME VARCHAR(16777216),
    TIER VARCHAR(16777216),
    STATUS VARCHAR(16777216),
    PREFERRED_CATEGORY VARCHAR(16777216),
    TOP_CATEGORY VARCHAR(16777216),
    TOP_BRAND VARCHAR(16777216),
    TOTAL_TRANSACTIONS NUMBER(38,0),
    TOTAL_SPEND_USD FLOAT,
    AVG_ORDER_VALUE FLOAT,
    LOYALTY_POINTS_BALANCE NUMBER(38,0),
    POINTS_REDEEMABLE_VALUE_USD FLOAT,
    TENURE_DAYS NUMBER(38,0),
    DAYS_SINCE_LAST_PURCHASE NUMBER(38,0),
    ESTIMATED_LTV_USD FLOAT,
    CHURN_RISK_SCORE FLOAT,
    CHURN_RISK_LEVEL VARCHAR(16777216) COMMENT 'HIGH, MEDIUM, LOW',
    CUSTOMER_SEGMENT VARCHAR(16777216) COMMENT 'VIP, LOYAL, AT_RISK, NEW, DORMANT',
    RECOMMENDED_ACTION VARCHAR(16777216) COMMENT 'RETAIN, UPSELL, RE_ENGAGE, ONBOARD'
)
    COMMENT = 'Gold layer. Analytics-ready customer loyalty insights with computed LTV, churn risk scoring, and customer segmentation. One row per loyalty member.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_PROMOTION_PERFORMANCE (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    GOLD_REFRESHED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PROMOTION_ID VARCHAR(16777216) NOT NULL,
    PROMOTION_NAME VARCHAR(16777216) NOT NULL,
    PROMOTION_TYPE VARCHAR(16777216),
    TARGET_CATEGORY VARCHAR(16777216),
    TARGET_BRAND VARCHAR(16777216),
    CHANNEL VARCHAR(16777216),
    START_DATE DATE,
    END_DATE DATE,
    PROMO_DURATION_DAYS NUMBER(38,0),
    STATUS VARCHAR(16777216),
    BUDGET_USD FLOAT,
    PLANNED_UNIT_LIFT_PCT FLOAT,
    PLANNED_REVENUE_TARGET_USD FLOAT,
    SKU_COUNT NUMBER(38,0),
    TOTAL_UNITS_DURING_PROMO NUMBER(38,0),
    BASELINE_UNITS_PER_WEEK FLOAT,
    ACTUAL_UNIT_LIFT_PCT FLOAT,
    TOTAL_REVENUE_DURING_PROMO FLOAT,
    BASELINE_REVENUE_PER_WEEK FLOAT,
    REVENUE_LIFT_PCT FLOAT,
    ESTIMATED_ROAS FLOAT,
    TOTAL_DISCOUNT_GIVEN_USD FLOAT,
    PERFORMANCE_STATUS VARCHAR(16777216) COMMENT 'OVER_PERFORMING, ON_TRACK, UNDER_PERFORMING'
)
    COMMENT = 'Gold layer. Promotion performance metrics computed by comparing promo-period sales vs pre-promo baseline for assigned SKUs. One row per promotion.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_RETURNS_MARGIN_ANALYSIS (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    GOLD_REFRESHED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SKU_ID VARCHAR(16777216) NOT NULL,
    PRODUCT_NAME VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    CATEGORY VARCHAR(16777216),
    TOTAL_RETURNS NUMBER(38,0),
    TOTAL_UNITS_SOLD NUMBER(38,0),
    RETURN_RATE_PCT FLOAT,
    TOTAL_REFUND_USD FLOAT,
    TOTAL_MARGIN_LOST_USD FLOAT,
    AVG_DAYS_TO_RETURN FLOAT,
    TOP_RETURN_REASON VARCHAR(16777216),
    TOP_RETURN_CONDITION VARCHAR(16777216),
    ONLINE_RETURN_PCT FLOAT,
    RECOMMENDED_ACTION VARCHAR(16777216) COMMENT 'VENDOR_RMA, DELIST, IMPROVE_LISTING, MONITOR, QC_REVIEW',
    RATIONALIZATION_FLAG BOOLEAN DEFAULT FALSE
)
    COMMENT = 'Gold layer. SKU-level return analysis with computed return rates, margin erosion, and rationalization recommendations. One row per SKU with at least one return.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_SKU_PRICING_INTELLIGENCE (
    DASHBOARD_RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    FEED_RUN_ID VARCHAR(16777216),
    GOLD_LAST_REFRESHED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SKU_ID VARCHAR(16777216) NOT NULL,
    PRODUCT_NAME VARCHAR(16777216) NOT NULL,
    CATEGORY VARCHAR(16777216),
    SUBCATEGORY VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    OUR_CURRENT_PRICE FLOAT,
    OUR_COST_PRICE FLOAT,
    OUR_MARGIN_PERCENTAGE FLOAT,
    OUR_MARGIN_AMOUNT_USD FLOAT,
    LOWEST_COMPETITOR_PRICE_FOUND FLOAT,
    HIGHEST_COMPETITOR_PRICE_FOUND FLOAT,
    NUMBER_OF_COMPETITORS_FOUND NUMBER(38,0),
    PRIMARY_COMPETITOR_NAME VARCHAR(16777216),
    PRIMARY_COMPETITOR_PRICE FLOAT,
    PRICE_GAP_VS_PRIMARY_COMPETITOR_PCT FLOAT,
    OVERALL_COMPETITIVE_POSITIONING_STATUS VARCHAR(16777216),
    REQUIRES_IMMEDIATE_PRICE_REVIEW BOOLEAN DEFAULT FALSE,
    CURRENT_STOCK_LEVEL NUMBER(38,0),
    STOCK_AVAILABILITY_STATUS VARCHAR(16777216),
    ESTIMATED_DAYS_UNTIL_STOCKOUT NUMBER(38,0),
    REQUIRES_REPLENISHMENT_ACTION BOOLEAN DEFAULT FALSE,
    CORTEX_AI_RECOMMENDATION_SUMMARY VARCHAR(16777216),
    CORTEX_AI_RECOMMENDED_ACTION_TYPE VARCHAR(16777216) COMMENT 'REPRICE, REPLENISH, PROMOTE, MONITOR, or NO_ACTION_NEEDED',
    CORTEX_AI_RECOMMENDATION_GENERATED_AT TIMESTAMP_LTZ(9)
)
    CHANGE_TRACKING = TRUE
    COMMENT = 'Gold layer. Primary source for dashboard pricing table. One row per active SKU reflecting latest feed run data with pre-joined competitor pricing, stock status, and Cortex AI recommendations.';

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_WEEKLY_BRAND_SELL_THROUGH (
    RECORD_ID VARCHAR(16777216) DEFAULT UUID_STRING(),
    GOLD_REFRESHED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    WEEK_START_DATE DATE NOT NULL,
    WEEK_NUMBER NUMBER(38,0) NOT NULL,
    BRAND VARCHAR(16777216) NOT NULL,
    TOTAL_UNITS_SOLD NUMBER(38,0) NOT NULL,
    TOTAL_REVENUE_USD FLOAT NOT NULL,
    SKU_COUNT NUMBER(38,0) NOT NULL,
    AVG_UNITS_PER_SKU FLOAT,
    FISCAL_QUARTER VARCHAR(16777216)
)
    COMMENT = 'Gold layer. Weekly sell-through aggregation by brand. Powers the 13-week trend chart on the Category Intelligence dashboard.';

-- ============================================================
-- SNAPSHOT TABLE — dbt snapshot (SCD Type 2, Transient)
-- ============================================================

DEFINE TABLE DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.SNAPSHOT_PRICING_INTELLIGENCE (
    SKU_ID VARCHAR(16777216),
    PRODUCT_NAME VARCHAR(16777216),
    CATEGORY VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    OUR_CURRENT_PRICE FLOAT,
    OUR_COST_PRICE FLOAT,
    OUR_MARGIN_PERCENTAGE FLOAT,
    PRIMARY_COMPETITOR_NAME VARCHAR(16777216),
    PRIMARY_COMPETITOR_PRICE FLOAT,
    PRICE_GAP_VS_PRIMARY_COMPETITOR_PCT FLOAT,
    OVERALL_COMPETITIVE_POSITIONING_STATUS VARCHAR(16777216),
    CURRENT_STOCK_LEVEL NUMBER(38,0),
    STOCK_AVAILABILITY_STATUS VARCHAR(16777216),
    CORTEX_AI_RECOMMENDED_ACTION_TYPE VARCHAR(16777216),
    DBT_SCD_ID VARCHAR(32),
    DBT_UPDATED_AT TIMESTAMP_NTZ(9),
    DBT_VALID_FROM TIMESTAMP_NTZ(9),
    DBT_VALID_TO TIMESTAMP_NTZ(9)
);
