-- Table definitions
-- Add your DEFINE TABLE statements here.

DEFINE TABLE SANDBOX.TPCH.CUSTOMERS (
    CUSTOMER_ID NUMBER NOT NULL,
    NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
    COMMENT = 'Customer master data';

DEFINE TABLE SANDBOX.TPCH.ORDERS (
    ORDER_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(12, 2),
    STATUS VARCHAR(20) DEFAULT 'PENDING'
)
    COMMENT = 'Order transactions'
    CHANGE_TRACKING = TRUE;
