-- View definitions
-- Add your DEFINE VIEW statements here.

DEFINE VIEW SANDBOX.TPCH.CUSTOMER_ORDER_SUMMARY AS
    SELECT
        c.CUSTOMER_ID,
        c.NAME,
        COUNT(o.ORDER_ID) AS TOTAL_ORDERS,
        SUM(o.TOTAL_AMOUNT) AS LIFETIME_VALUE,
        MAX(o.ORDER_DATE) AS LAST_ORDER_DATE
    FROM SANDBOX.TPCH.CUSTOMERS c
    LEFT JOIN SANDBOX.TPCH.ORDERS o
        ON c.CUSTOMER_ID = o.CUSTOMER_ID
    GROUP BY c.CUSTOMER_ID, c.NAME;
