-- ============================================================
-- DEFINE VIEW Definitions (DCM Managed)
-- Schema: DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
-- Layers: Staging / Intermediate / Analytics
-- ============================================================

-- ============================================================
-- STAGING VIEWS — 1:1 projections from Gold tables
-- ============================================================

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_CATEGORY_PERFORMANCE AS
    SELECT
        SUMMARY_RECORD_ID,
        FEED_RUN_ID,
        GOLD_LAST_REFRESHED_AT,
        CATEGORY,
        TOTAL_ACTIVE_SKUS_IN_CATEGORY,
        COUNT_OVERPRICED_SKUS,
        COUNT_UNDERPRICED_SKUS,
        COUNT_AT_PRICE_PARITY_SKUS,
        COUNT_OUT_OF_STOCK_SKUS,
        COUNT_LOW_STOCK_SKUS,
        AVERAGE_MARGIN_PERCENTAGE,
        TOTAL_INVENTORY_RETAIL_VALUE_USD,
        COUNT_SKUS_NEEDING_PRICE_ACTION,
        COUNT_SKUS_NEEDING_REPLENISHMENT
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_CATEGORY_PERFORMANCE_SUMMARY;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_LOYALTY_CUSTOMERS AS
    SELECT
        MEMBER_ID,
        FULL_NAME,
        TIER,
        STATUS,
        PREFERRED_CATEGORY,
        TOP_CATEGORY,
        TOP_BRAND,
        TOTAL_TRANSACTIONS,
        TOTAL_SPEND_USD,
        AVG_ORDER_VALUE,
        LOYALTY_POINTS_BALANCE,
        POINTS_REDEEMABLE_VALUE_USD,
        TENURE_DAYS,
        DAYS_SINCE_LAST_PURCHASE,
        ESTIMATED_LTV_USD,
        CHURN_RISK_SCORE,
        CHURN_RISK_LEVEL,
        CUSTOMER_SEGMENT,
        RECOMMENDED_ACTION
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_LOYALTY_CUSTOMER_INSIGHTS;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_PRICING_INTELLIGENCE AS
    SELECT
        DASHBOARD_RECORD_ID,
        FEED_RUN_ID,
        GOLD_LAST_REFRESHED_AT,
        SKU_ID,
        PRODUCT_NAME,
        CATEGORY,
        SUBCATEGORY,
        BRAND,
        OUR_CURRENT_PRICE,
        OUR_COST_PRICE,
        OUR_MARGIN_PERCENTAGE,
        OUR_MARGIN_AMOUNT_USD,
        LOWEST_COMPETITOR_PRICE_FOUND,
        HIGHEST_COMPETITOR_PRICE_FOUND,
        NUMBER_OF_COMPETITORS_FOUND,
        PRIMARY_COMPETITOR_NAME,
        PRIMARY_COMPETITOR_PRICE,
        PRICE_GAP_VS_PRIMARY_COMPETITOR_PCT,
        OVERALL_COMPETITIVE_POSITIONING_STATUS,
        REQUIRES_IMMEDIATE_PRICE_REVIEW,
        CURRENT_STOCK_LEVEL,
        STOCK_AVAILABILITY_STATUS,
        ESTIMATED_DAYS_UNTIL_STOCKOUT,
        REQUIRES_REPLENISHMENT_ACTION,
        CORTEX_AI_RECOMMENDATION_SUMMARY,
        CORTEX_AI_RECOMMENDED_ACTION_TYPE,
        CORTEX_AI_RECOMMENDATION_GENERATED_AT
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_SKU_PRICING_INTELLIGENCE;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_PROMOTION_PERFORMANCE AS
    SELECT
        PROMOTION_ID,
        PROMOTION_NAME,
        PROMOTION_TYPE,
        TARGET_CATEGORY,
        TARGET_BRAND,
        CHANNEL,
        START_DATE,
        END_DATE,
        PROMO_DURATION_DAYS,
        STATUS,
        BUDGET_USD,
        PLANNED_UNIT_LIFT_PCT,
        PLANNED_REVENUE_TARGET_USD,
        SKU_COUNT,
        TOTAL_UNITS_DURING_PROMO,
        BASELINE_UNITS_PER_WEEK,
        ACTUAL_UNIT_LIFT_PCT,
        TOTAL_REVENUE_DURING_PROMO,
        BASELINE_REVENUE_PER_WEEK,
        REVENUE_LIFT_PCT,
        ESTIMATED_ROAS,
        TOTAL_DISCOUNT_GIVEN_USD,
        PERFORMANCE_STATUS
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_PROMOTION_PERFORMANCE;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_RETURNS_MARGIN AS
    SELECT
        SKU_ID,
        PRODUCT_NAME,
        BRAND,
        CATEGORY,
        TOTAL_RETURNS,
        TOTAL_UNITS_SOLD,
        RETURN_RATE_PCT,
        TOTAL_REFUND_USD,
        TOTAL_MARGIN_LOST_USD,
        AVG_DAYS_TO_RETURN,
        TOP_RETURN_REASON,
        TOP_RETURN_CONDITION,
        ONLINE_RETURN_PCT,
        RECOMMENDED_ACTION,
        RATIONALIZATION_FLAG
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.GOLD_RETURNS_MARGIN_ANALYSIS;

-- ============================================================
-- INTERMEDIATE VIEWS — Pass-through from staging
-- ============================================================

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_CATEGORY_PERFORMANCE AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_CATEGORY_PERFORMANCE;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_LOYALTY_CUSTOMERS AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_LOYALTY_CUSTOMERS;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_PRICING_INTELLIGENCE AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_PRICING_INTELLIGENCE;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_PROMOTION_PERFORMANCE AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_PROMOTION_PERFORMANCE;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_RETURNS_MARGIN AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.STG_RETURNS_MARGIN;

-- ============================================================
-- ANALYTICS VIEWS — Consumer-facing views for Cortex Agent
-- ============================================================

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.CATEGORY_PERFORMANCE_ANALYTICS_VIEW AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_CATEGORY_PERFORMANCE;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.LOYALTY_CUSTOMER_ANALYTICS_VIEW AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_LOYALTY_CUSTOMERS;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.PRICING_INTELLIGENCE_ANALYTICS_VIEW AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_PRICING_INTELLIGENCE;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.PROMOTION_PERFORMANCE_ANALYTICS_VIEW AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_PROMOTION_PERFORMANCE;

DEFINE VIEW DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.RETURNS_MARGIN_ANALYTICS_VIEW AS
    SELECT *
    FROM DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INT_RETURNS_MARGIN;
