-- ============================================================
-- Task Definitions (Imperative — CREATE OR REPLACE)
-- Schema: DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT
-- Tasks are NOT DCM-managed. Deployed via CI pipeline.
--
-- DAG Structure:
--   DAILY_TRANSFORM_PIPELINE_TRIGGER (root, scheduled)
--     └─> TRANSFORM_BRONZE_TO_SILVER
--           └─> RUN_DATA_QUALITY_CHECKS
--                 └─> REFRESH_GOLD_ANALYTICS_LAYER
--
--   INGEST_COMPETITOR_PRICES_FROM_SERPAPI_TASK (standalone, manual)
-- ============================================================

-- Root task: Daily pipeline trigger (runs at 6:00 AM UTC)
CREATE OR REPLACE TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.DAILY_TRANSFORM_PIPELINE_TRIGGER
    WAREHOUSE = RETAIL_CATEGORY_ANALYTICS_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
    COMMENT = 'Root trigger for the daily Bronze to Silver to DQ to Gold transform pipeline'
AS
    SELECT 'DAILY_TRANSFORM_PIPELINE_STARTED' AS status;

-- Child task: Bronze to Silver transformation
CREATE OR REPLACE TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.TRANSFORM_BRONZE_TO_SILVER
    WAREHOUSE = RETAIL_CATEGORY_ANALYTICS_WH
    AFTER DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.DAILY_TRANSFORM_PIPELINE_TRIGGER
    COMMENT = 'Transforms raw Bronze SKU and competitor price data into cleansed Silver tables'
AS
    CALL DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.TRANSFORM_BRONZE_TO_SILVER_PIPELINE();

-- Child task: Data quality checks on Silver layer
CREATE OR REPLACE TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.RUN_DATA_QUALITY_CHECKS
    WAREHOUSE = RETAIL_CATEGORY_ANALYTICS_WH
    AFTER DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.TRANSFORM_BRONZE_TO_SILVER
    COMMENT = 'Runs data quality validation suite against Silver layer (informational, does not block Gold)'
AS
    CALL DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.RUN_DATA_QUALITY_VALIDATION_SUITE('TASK_SCHEDULED');

-- Child task: Refresh Gold analytics layer
CREATE OR REPLACE TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.REFRESH_GOLD_ANALYTICS_LAYER
    WAREHOUSE = RETAIL_CATEGORY_ANALYTICS_WH
    AFTER DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.RUN_DATA_QUALITY_CHECKS
    COMMENT = 'Refreshes Gold pricing intelligence dashboard and category performance summary with AI recommendations'
AS
    CALL DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.REFRESH_GOLD_LAYER_PIPELINE(NULL);

-- Standalone task: SerpAPI competitor price ingestion (manual trigger only)
CREATE OR REPLACE TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INGEST_COMPETITOR_PRICES_FROM_SERPAPI_TASK
    WAREHOUSE = RETAIL_CATEGORY_ANALYTICS_WH
    COMMENT = 'Fetches competitor prices from SerpAPI into Bronze layer (manual trigger only - preserves API credits)'
AS
    CALL DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.INGEST_COMPETITOR_PRICES_FROM_SERPAPI('TASK_MANUAL_TRIGGER', 100);

-- ============================================================
-- Resume DAG tasks after deployment:
-- ALTER TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.REFRESH_GOLD_ANALYTICS_LAYER RESUME;
-- ALTER TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.RUN_DATA_QUALITY_CHECKS RESUME;
-- ALTER TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.TRANSFORM_BRONZE_TO_SILVER RESUME;
-- ALTER TASK DEMO_DEV.RETAIL_CATEGORY_ANALYTICS_AGENT.DAILY_TRANSFORM_PIPELINE_TRIGGER RESUME;
-- ============================================================
