SELECT
    TIER,
    CHURN_RISK_LEVEL,
    CUSTOMER_SEGMENT,
    COUNT(*) AS MEMBER_COUNT,
    ROUND(AVG(TOTAL_SPEND_USD), 2) AS AVG_SPEND,
    ROUND(AVG(ESTIMATED_LTV_USD), 2) AS AVG_LTV,
    ROUND(AVG(DAYS_SINCE_LAST_PURCHASE), 0) AS AVG_DAYS_INACTIVE,
    ROUND(AVG(CHURN_RISK_SCORE), 3) AS AVG_CHURN_SCORE
FROM {{ ref('loyalty_customer_analytics_view') }}
GROUP BY TIER, CHURN_RISK_LEVEL, CUSTOMER_SEGMENT
ORDER BY CHURN_RISK_LEVEL DESC, MEMBER_COUNT DESC
