SELECT
    SKU_ID,
    PRODUCT_NAME,
    BRAND,
    CATEGORY,
    OUR_CURRENT_PRICE,
    PRIMARY_COMPETITOR_PRICE,
    PRICE_GAP_VS_PRIMARY_COMPETITOR_PCT,
    OVERALL_COMPETITIVE_POSITIONING_STATUS,
    CURRENT_STOCK_LEVEL,
    CORTEX_AI_RECOMMENDED_ACTION_TYPE,
    CASE
        WHEN REQUIRES_IMMEDIATE_PRICE_REVIEW AND REQUIRES_REPLENISHMENT_ACTION THEN 'CRITICAL'
        WHEN REQUIRES_IMMEDIATE_PRICE_REVIEW THEN 'HIGH'
        WHEN PRICE_GAP_VS_PRIMARY_COMPETITOR_PCT > 10 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS PRIORITY_LEVEL
FROM {{ ref('pricing_intelligence_analytics_view') }}
WHERE OVERALL_COMPETITIVE_POSITIONING_STATUS = 'OVERPRICED'
   OR REQUIRES_IMMEDIATE_PRICE_REVIEW = TRUE
ORDER BY ABS(PRICE_GAP_VS_PRIMARY_COMPETITOR_PCT) DESC NULLS LAST
