SELECT
    BRAND,
    CATEGORY,
    COUNT(*) AS SKU_COUNT,
    SUM(TOTAL_RETURNS) AS TOTAL_RETURNS,
    SUM(TOTAL_UNITS_SOLD) AS TOTAL_UNITS_SOLD,
    ROUND(SUM(TOTAL_RETURNS) * 100.0 / NULLIF(SUM(TOTAL_UNITS_SOLD), 0), 2) AS RETURN_RATE_PCT,
    ROUND(SUM(TOTAL_MARGIN_LOST_USD), 2) AS TOTAL_MARGIN_LOST_USD,
    ROUND(SUM(TOTAL_REFUND_USD), 2) AS TOTAL_REFUND_USD,
    ROUND(AVG(AVG_DAYS_TO_RETURN), 1) AS AVG_DAYS_TO_RETURN
FROM {{ ref('returns_margin_analytics_view') }}
GROUP BY BRAND, CATEGORY
HAVING SUM(TOTAL_RETURNS) > 0
ORDER BY TOTAL_MARGIN_LOST_USD DESC
